var defaultLang={
    //English by RX-3200.
    saveBtn: "OK",
    download:"Download",
    saveBtnTips: "some options need to refresh the page to take effect",
    closeBtn: "Cancel",
    invertBtn:"Invert",
    closeBtnTips: "cancel this setting and restore all options",
    resetLink: "Restore default settings",
    resetLinkTips: "restore all settings to default values",
    share:"Share",
    suitLongImg:"Suit long pics in scroll window",
    globalkeys:"Global keys for preview: ",
    globalkeysPress:"Press to toggle preview",
    globalkeysHold:"Hold to enable preview",
    globalkeysType:"Method to enable preview",
    loadAll:"Load more pages",
    loadedAll:"Load completed",
    loading:"Loading ...",
    loadAllTip:"Load the picture on the next page",
    viewmoreEndless:"Load more pics in viewmore when scroll to bottom",
    fiddle:"Operate",
    fiddleTip:"Pop-up pictures for complex operations",
    closeFirst:"Close the existing Gallery first",
    collect:"Collection",
    collected:"Has been collected",
    exitCollection:"Exit collection",
    exitCollectionTip:"Click to exit the collection mode",
    noCollectionYet:"You have no picture in the collection",
    collectDetail:"Description",
    collectDetailTip:"Add some descriptions to your favorite pictures",
    playSlide:"Play slideshow",
    slideGap:"Interval (s)",
    slideGapTip:"Interval, unit (seconds)",
    slideBack:"Back",
    slideBackTip:"Play from back to front",
    slideWait:"Wait for image reading",
    slideWaitTip:"The countdown starts after each image is completely read.",
    slideSkipError:"Skip error pictures",
    slideSkipErrorTip:"Quickly skip to read the error pictures",
    type:"Category",
    typeTip:"Select image category",
    advancedRules:"Advanced Rules",
    advancedRulesTip:"Matched by advanced rules",
    tpRules:"Wildcard rules",
    tpRulesTip:"Matched by wildcard rules",
    scaleRules:"Zoomed",
    scaleRulesTip:"The image which is finded automatically but scaled",
    noScaleRules:"No scaling",
    noScaleRulesTip:"The image which is finded automatically but without scale",
    smallRules:"Small size",
    smallRulesTip:"Small size image, the actual size of the height and width are less than #t# pixels",
    lockSizeTip:"Lock the max size",
    command:"Command",
    commandTip:"Command Menu",
    onlineEdit:"Online editing",
    onlineEditTip:"Edit this image online using #t#",
    openInNewWindow:"Open in new window",
    openInNewWindowTip:"Open image in new window",
    findInPage:"Find In Page",
    findInPageTip:"Scroll to the current image in page",
    viewCollection:"View Collection",
    viewCollectionTip:"View all collected images",
    inCollection:"Unable to use in Collection mode",
    cantFind:"The image is not in the document, or it is hidden and cannot be located!",
    exportImages:"Export all Images",
    exportImagesTip:"Export all shown big size images to new window",
    downloadImage:"Download all shown",
    downloadImageTip:"Download the current shown pictures",
    copyImagesUrl:"Copy all images Urls",
    copyImagesUrlTip:"Copy all shown big size image Urls",
    copySuccess:"Copied #t# Urls successfully",
    autoRefresh:"Auto load page",
    autoRefreshTip:"When the last few images are viewed, scroll the window to the bottom, so that some webpage will load the new images",
    enterFullsc:"Enter full screen",
    exitFullsc:"Exit full screen",
    config:"Settings",
    openConfig:"Open Settings",
    closeGallery:"Close Gallery",
    returnToGallery:"Back to the Gallery",
    picInfo:"Click to change",
    picNote:"Img annotation",
    urlFilter:"Url filter",
    urlFilterTip:"Input key words or Regexp to filter Urls",
    resolution:"Img Resolution",
    picNum:"Number of pictures",
    picTips:"View pictures with CTRL key",
    savePageTips:"Save this page to download all pics",
    scaleRatio:"Scaling ratio",
    similarImage:"Searching by image",
    scale:"Zoom",
    horizontalFlip:"Horizontal flip",
    verticalFlip:"Vertical flip",
    actualBtn:"View original (A)",
    searchBtn:"Find the original image (S)",
    galleryBtn:"View gallery (G)",
    currentBtn:"View current (C)",
    magnifierBtn:"Magnifier / ZooM (M)",
    picTitle:"Picture Title",
    exportImagesUrl:"Export image Url",
    exportImagesUrlPop:"Ctrl+C to copy image Url",
    beginSearchImg:"#t# begin Search Img ...",
    findNoPic:"The original image was not found",
    findOverBeginLoad:"#t# end of the map, find #t# matching pictures, start loading the first one",
    loadNextSimilar:"The original image failed to load, try to load the next result...",
    loadError:"Load failed",
    openHomePage:"Open Home page",
    position:"Display position",
    positionTips:"Hold ALT to hide",
    topLeft:"The top left corner of the picture",
    topRight:"The top right corner of the picture",
    bottomRight:"The bottom right corner of the picture",
    bottomLeft:"The bottom left corner of the picture",
    topCenter:"Beside the picture",
    bottomCenter:"Below the picture",
    floatBar:"Toolbar",
    showDelay:"Show delay",
    ms:"ms",
    hide:"Hide",
    hideDelay:"Hide delay",
    forceShow:"Show toolbar over Non-zoomed image beyond that size, ",
    forceShowTip:"Show floating toolbar when non-scaled image size exceeds the size set below",
    sizeLimitOr:"Effected by height OR width only",
    px:"px",
    minSizeLimit:"Show toolbar over Zoomed image beyond that size",
    minSizeLimitTip:"After the image is scaled (the original size of the image does not match the actual size), the floating toolbar is displayed when the shown image length is greater than the set value.",
    defaultSizeLimit:"Default size limit for gallery",
    listenBg:"Listening background image",
    listenBgTip:"Show toolbar on the element with the background image",
    butonOrder:"Sort of toolbar icons",
    keysEnable:"Enable shortcuts",
    keysActual:"Open the big picture",
    keysActualTip:"Press this button to open a large image when floating bar appears",
    keysSearch:"Find the original image",
    keysSearchTip:"Press this button to find the original image when floating bar appears",
    headSearchTip:"Search by image",
    headSearchAll:"Search All",
    keysCurrent:"Open the current picture",
    keysCurrentTip:"Press this button to open the current image when floating bar appears",
    keysMagnifier:"Open the magnifier to observe",
    keysMagnifierTip:"Press this button to open the magnifier when floating bar appears",
    keysGallery:"Open Gallery（Global with funcKeys）",
    keysGalleryTip:"Press this button to open the Gallery when floating bar appears",
    openGallery:"Open Gallery",
    magnifier:"Zoom",
    magnifierRadius:"Default radius",
    magnifierWheelZoomEnabled:"Enable wheel zoom",
    magnifierWheelZoomRange:"Zoom ratio for magnifier",
    gallery:"Gallery",
    galleryFitToScreen:"Scale the image to fit the screen",
    galleryFitToScreenSmall:"Scale the small image also",
    galleryFitToScreenTip:"Adapt to be contain, not cover",
    galleryScrollEndToChange:"Switch the image after the long picture scrolls to the end",
    galleryScrollEndToChangeTip:"Valid after canceling the previous option",
    galleryExportType:"Default sort when images exported",
    grid:"Tile sorting",
    gridBig:"original sorting",
    list:"List sorting",
    galleryAutoLoad:"Automatically load more images on next page",
    galleryLoadAll:"Automatically process all pages when loading more images",
    galleryLoadAllTip:"Too many pages may affect the experience",
    galleryDownloadWithZip:"Compress to ZIP when download all",
    galleryDownloadWithZipAlert:"Compressing, wait for a while please",
    galleryScaleSmallSize1:"The actual size is less than the height and width",
    galleryScaleSmallSize2:"Pixels are grouped into small size images",
    galleryShowSmallSize:"Show small size pictures by default",
    galleryTransition:"Show effects when gallery switch",
    gallerySidebarPosition:"Thumbnail bar position",
    bottom:"Bottom",
    right:"Right",
    left:"Left",
    top:"Top",
    gallerySidebarSize:"Height",
    gallerySidebarSizeTip:"The height of the thumbnail bar (if it is horizontal) or the width (if it is vertical)",
    galleryMax1:"Maximum prefetch",
    galleryMax2:"Pictures (before and after)",
    galleryAutoZoom:"Zoom changes back to 100% (chrome)",
    galleryAutoZoomTip:"If you zoom in, change the zoom of the image and sidebar sections back to 100% and increase the viewable area (only valid under chrome)",
    galleryDescriptionLength1:"Maximum of annotation is",
    galleryDescriptionLength2:"Characters",
    galleryAutoOpenSites:"Regulars of urls for auto open gallery, one per line, start with @ for ViewMore",
    autoOpenViewmore:"Auto view more when open gallery",
    galleryViewmoreLayout:"Layout of ViewMore mode",
    gallerySearchData:"Site rules for search, empty it to restore",
    galleryEditSite:"Online editing site",
    imgWindow:"ImgWindow",
    imgWindowFitToScreen:"Adapt to the screen",
    imgWindowFitToScreenTip:"Adapt to be contain, not cover",
    imgWindowDefaultTool:"The tool selected by default when opening the window",
    hand:"Hand",
    rotate:"Rotate",
    zoom:"Magnifier",
    imgWindowEscKey:"Esc key to close",
    imgWindowDblClickImgWindow:"Double click to close",
    imgWindowClickOutside:"Click overlayer to close by",
    imgWindowClickOutsideTip:"Only enable when Overlayer is shown",
    none:"None",
    click:"Click",
    dblclick:"Double click",
    imgWindowOverlayerShown:"Overlay",
    imgWindowOverlayerColor:"Color and Opacity",
    imgWindowShiftRotateStep1:"Rotate when hold down the Shift key on every ",
    imgWindowShiftRotateStep2:"Degree",
    imgWindowMouseWheelZoom:"MouseWheel Zoom",
    imgWindowZoomRange:"Zoom Range",
    imgWindowZoomRangeTip:"Zoom ratio (must be positive)",
    others:"Other",
    waitImgLoad:"Start to perform operations such as zooming until image is loaded",
    waitImgLoadTip:"When holding down the Ctrl key, you can temporarily execute opposite to this setting",
    debug:"Debug mode",
    customRules:"Custom rules for large image",
    firstEngine:"Preferred (first) search engine",
    refreshWhenError:"Read error, click to overload",
    switchSlide:"Switch sidebar",
    viewmore:"View more",
    countDown:"CountDown",
    customLang:"Custom language",
    defaultLang:"Auto detect",
    toggleIcon:"Toggle icon",
    initShow:"Invert Shortcut to show preview by default",
    stayOut:"Let float bar stay out of the image"
};
var zhCNLang={
    saveBtn:"确定",
    download:"下载",
    saveBtnTips:"部分选项需要刷新页面才能生效",
    closeBtn:"取消",
    invertBtn:"反选",
    closeBtnTips:"取消本次设置，所有选项还原",
    resetLink:"恢复默认设置",
    resetLinkTips:"恢复所有设置的内容为默认值",
    share:"分享",
    suitLongImg:"长图在滚动窗口显示",
    globalkeys:"预览功能键组合: ",
    globalkeysPress:"敲击切换预览",
    globalkeysHold:"按住开启预览",
    globalkeysType:"预览触发方式：",
    loadAll:"加载更多页",
    loadedAll:"加载完毕",
    loading:"正在加载",
    loadAllTip:"加载下一页的图片",
    viewmoreEndless:"查看更多里滚动到底自动加载下一页",
    fiddle:"折腾",
    fiddleTip:"弹出图片进行复杂操作",
    closeFirst:"请先关掉当前已经打开的库",
    collect:"收藏",
    collected:"已收藏",
    exitCollection:"退出收藏",
    exitCollectionTip:"点击退出收藏模式",
    noCollectionYet:"你还木有收藏任何图片",
    collectDetail:"描述",
    collectDetailTip:"给收藏的图片添加一些描述吧",
    playSlide:"播放幻灯片",
    slideGap:"间隔(s)",
    slideGapTip:"间隔时间，单位(秒)",
    slideBack:"后退",
    slideBackTip:"从后往前播放",
    slideWait:"等待图片读取",
    slideWaitTip:"从每张图片完全读取完成后才开始倒计时",
    slideSkipError:"跳过错误图片",
    slideSkipErrorTip:"快速跳过读取错误的图片",
    type:"类别",
    typeTip:"选择图片类别",
    advancedRules:"高级规则",
    advancedRulesTip:"由高级规则匹配出来的",
    tpRules:"通配规则",
    tpRulesTip:"由通配规则匹配出来的",
    scaleRules:"缩放过的",
    scaleRulesTip:"js自动查找，相对页面显示的图片有缩放过的",
    noScaleRules:"无缩放过",
    noScaleRulesTip:"js自动查找，无缩放过的，但是满足一定的大小",
    smallRules:"小尺寸的",
    smallRulesTip:"小尺寸图片，实际尺寸的高和宽都小于#t#像素",
    lockSizeTip:"锁定最大尺寸",
    command:"命令",
    commandTip:"命令菜单",
    onlineEdit:"在线编辑",
    onlineEditTip:"使用#t#在线编辑该图片",
    openInNewWindow:"新窗口打开",
    openInNewWindowTip:"新窗口打开图片",
    findInPage:"定位到图片",
    findInPageTip:"滚动到当前图片所在的位置",
    viewCollection:"查看收藏",
    viewCollectionTip:"查看所有收藏的图片",
    inCollection:"收藏模式中，无法使用",
    cantFind:"图片不在文档中，或者被隐藏了，无法定位！",
    exportImages:"导出显示大图",
    exportImagesTip:"导出所有显示中的图片到新窗口",
    downloadImage:"下载当前所有",
    downloadImageTip:"下载当前库中所有显示图片",
    copyImagesUrl:"复制显示大图",
    copyImagesUrlTip:"复制所有显示中的大图地址",
    copySuccess:"已成功复制 #t# 张大图地址",
    autoRefresh:"自动重载",
    autoRefreshTip:"最后几张图片时，滚动主窗口到最底部，然后自动加载新的图片",
    enterFullsc:"进入全屏",
    exitFullsc:"退出全屏",
    config:"设置",
    openConfig:"打开设置",
    closeGallery:"关闭库",
    returnToGallery:"回到库",
    picInfo:"点击修改",
    picNote:"图片注释",
    urlFilter:"过滤链接",
    urlFilterTip:"输入关键字或正则表达式过滤链接",
    resolution:"分辨率",
    scaleRatio:"缩放比",
    similarImage:"以图搜图",
    scale:"缩放",
    horizontalFlip:"水平翻转",
    verticalFlip:"垂直翻转",
    actualBtn:'查看原始(A)',
    searchBtn:'查找原图(S)',
    galleryBtn:'查看库(G)',
    currentBtn:'查看当前(C)',
    magnifierBtn:'放大镜(M)',
    picTitle:"图片标题",
    picNum:"图片数量",
    picTips:"按住Ctrl放大",
    savePageTips:"使用“网页另存为”即可保存所有图片",
    exportImagesUrl:"导出图片链接",
    exportImagesUrlPop:"Ctrl+C复制图片链接",
    beginSearchImg:"#t#识图开始……",
    findNoPic:"未找到原图",
    findOverBeginLoad:"#t#识图结束，共找到#t#张匹配图片，开始加载第一张",
    loadNextSimilar:"原图加载失败，尝试加载下一结果……",
    loadError:"加载失败",
    openHomePage:"点击此处打开主页",
    position:"显示位置",
    positionTips:"按住ALT隐藏",
    topLeft: '图片左上角',
    topRight: '图片右上角',
    bottomRight: '图片右下角',
    bottomLeft: '图片左下角',
    topCenter: '图片正上方',
    bottomCenter: '图片正下方',
    floatBar:"浮动工具栏",
    showDelay:"显示延时",
    ms:"毫秒",
    hide:"隐藏",
    hideDelay:"隐藏延时",
    forceShow:"非缩放图片，超过该尺寸，显示浮框",
    forceShowTip:"非缩放的图片大小超过下面设定的尺寸时显示浮动工具栏",
    sizeLimitOr:"以上长宽条件只需满足其一",
    px:"像素",
    minSizeLimit:"缩放图片，超过该尺寸，显示浮框",
    minSizeLimitTip:"图片被缩放(图片原始大小与实际大小不一致)后,显示长宽大于设定值时显示浮动工具栏",
    defaultSizeLimit:"图库默认筛选尺寸",
    listenBg:"监听背景图",
    listenBgTip:"在有背景图的元素上显示悬浮框",
    butonOrder:"工具栏图标排序",
    keysEnable:"启用以下快捷键",
    keysActual:"打开大图",
    keysActualTip:"当出现悬浮条时按下此按键打开大图",
    keysSearch:"查找原图",
    keysSearchTip:"当出现悬浮条时按下此按键查找原图",
    headSearchTip:"搜图",
    headSearchAll:"搜索以上全部",
    keysCurrent:"打开当前图片",
    keysCurrentTip:"当出现悬浮条时按下此按键打开当前显示的图片",
    keysMagnifier:"打开放大镜观察",
    keysMagnifierTip:"当出现悬浮条时按下此按键打开放大镜观察",
    keysGallery:"打开图库（加功能键为全局）",
    keysGalleryTip:"当出现悬浮条时按下此按键打开图库",
    openGallery:"打开图库",
    magnifier:"放大镜",
    magnifierRadius:"默认半径",
    magnifierWheelZoomEnabled:"启用滚轮缩放",
    magnifierWheelZoomRange:"滚轮缩放的倍率",
    gallery:"图库",
    galleryFitToScreen:"对图片进行缩放以适应屏幕",
    galleryFitToScreenSmall:"小图也缩放以适应屏幕",
    galleryFitToScreenTip:"适应方式为contain，非cover",
    galleryScrollEndToChange:"大图滚动到底后切换图片",
    galleryScrollEndToChangeTip:"取消上一选项后才有效",
    galleryExportType:"图片导出默认排序",
    grid:'平铺排序',
    gridBig:'原图平铺',
    list:'列表排序',
    galleryAutoLoad:"自动加载更多图片",
    galleryLoadAll:"加载更多图片时自动处理全部页",
    galleryLoadAllTip:"若页数过多可能影响体验",
    galleryDownloadWithZip:"下载所有时打包成zip",
    galleryDownloadWithZipAlert:"正在打包，请耐心等候数十秒",
    galleryScaleSmallSize1:"实际尺寸的高和宽都小于 ",
    galleryScaleSmallSize2:" 像素则归入小尺寸图片",
    galleryShowSmallSize:"默认显示小尺寸图片",
    galleryTransition:"显示图库切换图片的特效",
    gallerySidebarPosition:"缩略图栏位置",
    bottom:'底部',
    right:'右侧',
    left:'左侧',
    top:'顶部',
    gallerySidebarSize:"高度",
    gallerySidebarSizeTip:"缩略图栏的高（如果是水平放置）或者宽（如果是垂直放置）",
    galleryMax1:"最多预读 ",
    galleryMax2:" 张图片（前后各多少张）",
    galleryAutoZoom:"缩放改回 100%（chrome）",
    galleryAutoZoomTip:"如果有放大，则把图片及 sidebar 部分的缩放改回 100%，增大可视面积（仅在 chrome 下有效）",
    galleryDescriptionLength1:"注释的最大宽度",
    galleryDescriptionLength2:" 个字符",
    galleryAutoOpenSites:"自动打开图库的网址正则，一行一条，若开头加@则自动展开图库",
    autoOpenViewmore:"打开图库时自动展开",
    galleryViewmoreLayout:"图库展开之后的布局",
    gallerySearchData:"搜图站点设置，清空还原",
    galleryEditSite:"在线编辑站点",
    imgWindow:"图片窗口",
    imgWindowFitToScreen:"适应屏幕，并且水平垂直居中",
    imgWindowFitToScreenTip:"适应方式为contain，非cover",
    imgWindowDefaultTool:"打开窗口时默认选择的工具",
    hand:'抓手',
    rotate:'旋转',
    zoom:'放大镜',
    imgWindowEscKey:"Esc键关闭",
    imgWindowDblClickImgWindow:"双击图片窗口关闭",
    imgWindowClickOutside:"点击图片外部（覆盖层）关闭",
    imgWindowClickOutsideTip:"仅当覆盖层显示时生效",
    none:'无',
    click:'单击',
    dblclick:'双击',
    imgWindowOverlayerShown:"覆盖层",
    imgWindowOverlayerColor:"颜色和不透明度",
    imgWindowShiftRotateStep1:"旋转时，按住shift键，旋转的步进",
    imgWindowShiftRotateStep2:" 度",
    imgWindowMouseWheelZoom:"滚轮缩放",
    imgWindowZoomRange:"滚轮缩放比例",
    imgWindowZoomRangeTip:"缩放比例(必须为正数)",
    others:"其它",
    waitImgLoad:"等图片完全载入后，才开始执行弹出放大等操作",
    waitImgLoadTip:"按住ctrl键的时候,可以临时执行和这个设定相反的设定",
    debug:"调试模式",
    customRules:"自定义大图规则",
    firstEngine:"首选搜图引擎",
    refreshWhenError:"读取错误，点击重载",
    switchSlide:"开关侧边栏",
    viewmore:"展开更多",
    countDown:"倒计时",
    customLang:"设定语言",
    defaultLang:"自动选择",
    toggleIcon:"隐藏图标",
    initShow:"反转快捷键，默认显示预览",
    stayOut:"使浮动工具栏显示在图片外部"
};
var zhTWLang={
    saveBtn:"確定",
    download:"下載",
    saveBtnTips:"部分選項需要刷新頁面才能生效",
    closeBtn:"取消",
    invertBtn:"反選",
    closeBtnTips:"取消本次設置，所有選項還原",
    resetLink:"恢復默認設置",
    resetLinkTips:"恢復所有設置的內容為默認值",
    share:"分享",
    suitLongImg:"長圖在滾動窗口顯示",
    globalkeys:"預覽功能鍵組合: ",
    globalkeysPress:"敲擊切換預覽",
    globalkeysHold:"按住開啟預覽",
    globalkeysType:"預覽觸發方式：",
    loadAll:"載入更多",
    loadedAll:"載入完畢",
    loading:"正在載入",
    loadAllTip:"載入下一頁的圖片",
    viewmoreEndless:"查看更多裏滾動到底自動加載下一頁",
    fiddle:"折騰",
    fiddleTip:"彈出圖片進行複雜操作",
    closeFirst:"請先關閉當前已經打開的庫",
    collect:"收藏",
    collected:"已收藏",
    exitCollection:"退出收藏",
    exitCollectionTip:"點擊退出收藏模式",
    noCollectionYet:"你還木有收藏任何圖片",
    collectDetail:"描述",
    collectDetailTip:"給收藏的圖片添加一些描述吧",
    playSlide:"播放幻燈片",
    slideGap:"間隔(s)",
    slideGapTip:"間隔時間，單位(秒)",
    slideBack:"後退",
    slideBackTip:"從後往前播放",
    slideWait:"等待圖片讀取",
    slideWaitTip:"從每張圖片完全讀取完成後才開始倒計時",
    slideSkipError:"跳過錯誤圖片",
    slideSkipErrorTip:"快速跳過讀取錯誤的圖片",
    type:"類別",
    typeTip:"選擇圖片類別",
    advancedRules:"高級規則",
    advancedRulesTip:"由高級規則匹配出來的",
    tpRules:"通配規則",
    tpRulesTip:"由通配規則匹配出來的",
    scaleRules:"縮放過的",
    scaleRulesTip:"js自動查找，相對頁面顯示的圖片有縮放過的",
    noScaleRules:"無縮放過",
    noScaleRulesTip:"js自動查找，無縮放過的，但是滿足一定的大小",
    smallRules:"小尺寸的",
    smallRulesTip:"小尺寸圖片，實際尺寸的高和寬都小於#t#像素",
    lockSizeTip:"鎖定最大尺寸",
    command:"命令",
    commandTip:"命令菜單",
    onlineEdit:"在線編輯",
    onlineEditTip:"使用#t#在線編輯該圖片",
    openInNewWindow:"新窗口打開",
    openInNewWindowTip:"新窗口打開圖片",
    findInPage:"定位到圖片",
    findInPageTip:"滾動到當前圖片所在的位置",
    viewCollection:"查看收藏",
    viewCollectionTip:"查看所有收藏的圖片",
    inCollection:"收藏模式中，無法使用",
    cantFind:"圖片不在文檔中，或者被隱藏了，無法定位！",
    exportImages:"導出顯示大圖",
    exportImagesTip:"導出所有顯示中的圖片到新窗口",
    downloadImage:"下載當前所有",
    downloadImageTip:"下載當前庫中所有顯示圖片",
    copyImagesUrl:"複製顯示大圖",
    copyImagesUrlTip:"複製所有顯示中的大圖地址",
    copySuccess:"已成功複製 #t# 張大圖地址",
    autoRefresh:"自動重載",
    autoRefreshTip:"最後幾張圖片時，滾動主窗口到最底部，然後自動載入新的圖片",
    enterFullsc:"進入全屏",
    exitFullsc:"退出全屏",
    config:"設置",
    openConfig:"打開設置",
    closeGallery:"關閉庫",
    returnToGallery:"回到庫",
    picInfo:"點擊修改",
    picNote:"圖片注釋",
    urlFilter:"過濾連結",
    urlFilterTip:"輸入關鍵字或正則表達式過濾連結",
    resolution:"解析度",
    scaleRatio:"縮放比",
    similarImage:"以圖搜圖",
    scale:"縮放",
    horizontalFlip:"水平翻轉",
    verticalFlip:"垂直翻轉",
    actualBtn:'查看原始(A)',
    searchBtn:'查找原圖(S)',
    galleryBtn:'查看庫(G)',
    currentBtn:'查看當前(C)',
    magnifierBtn:'放大鏡(M)',
    picTitle:"圖片標題",
    picNum:"圖片數量",
    picTips:"按住Ctrl放大",
    savePageTips:"使用「網頁另存為」即可保存所有圖片",
    exportImagesUrl:"導出圖片鏈接",
    exportImagesUrlPop:"Ctrl+C複製圖片鏈接",
    beginSearchImg:"#t#識圖開始……",
    findNoPic:"未找到原圖",
    findOverBeginLoad:"#t#識圖結束，共找到#t#張匹配圖片，開始載入第一張",
    loadNextSimilar:"原圖載入失敗，嘗試載入下一結果……",
    loadError:"載入失敗",
    openHomePage:"點擊此處打開主頁",
    position:"顯示位置",
    positionTips:"按住ALT隱藏",
    topLeft: '圖片左上角',
    topRight: '圖片右上角',
    bottomRight: '圖片右下角',
    bottomLeft: '圖片左下角',
    topCenter: '圖片正上方',
    bottomCenter: '圖片正下方',
    floatBar:"浮動工具欄",
    showDelay:"顯示延時",
    ms:"毫秒",
    hide:"隱藏",
    hideDelay:"隱藏延時",
    forceShow:"非縮放圖片，超過該尺寸，顯示浮框",
    forceShowTip:"非縮放的圖片大小超過下面設定的尺寸時顯示浮動工具欄",
    sizeLimitOr:"以上長寬條件只需滿足其一",
    px:"像素",
    minSizeLimit:"縮放圖片，超過該尺寸，顯示浮框",
    minSizeLimitTip:"圖片被縮放(圖片原始大小與實際大小不一致)後,顯示長寬大於設定值時顯示浮動工具欄",
    defaultSizeLimit:"圖庫默認篩選尺寸",
    listenBg:"監聽背景圖",
    listenBgTip:"在有背景圖的元素上顯示懸浮框",
    butonOrder:"工具欄圖標排序",
    keysEnable:"啟用以下快捷鍵",
    keysActual:"打開大圖",
    keysActualTip:"當出現懸浮條時按下此按鍵打開大圖",
    keysSearch:"查找原圖",
    keysSearchTip:"當出現懸浮條時按下此按鍵查找原圖",
    headSearchTip:"搜圖",
    headSearchAll:"搜索以上全部",
    keysCurrent:"打開當前圖片",
    keysCurrentTip:"當出現懸浮條時按下此按鍵打開當前顯示的圖片",
    keysMagnifier:"打開放大鏡觀察",
    keysMagnifierTip:"當出現懸浮條時按下此按鍵打開放大鏡觀察",
    keysGallery:"打開圖庫（加功能鍵為全局）",
    keysGalleryTip:"當出現懸浮條時按下此按鍵打開圖庫",
    openGallery:"打開圖庫",
    magnifier:"放大鏡",
    magnifierRadius:"默認半徑",
    magnifierWheelZoomEnabled:"啟用滾輪縮放",
    magnifierWheelZoomRange:"滾輪縮放的倍率",
    gallery:"圖庫",
    galleryFitToScreen:"對圖片進行縮放以適應屏幕",
    galleryFitToScreenSmall:"小圖也縮放以適應屏幕",
    galleryFitToScreenTip:"適應方式為contain，非cover",
    galleryScrollEndToChange:"大圖滾動到底後切換圖片",
    galleryScrollEndToChangeTip:"取消上一選項後才有效",
    galleryExportType:"圖片導出默認排序",
    grid:'平鋪排序',
    gridBig:'原圖平鋪',
    list:'列表排序',
    galleryAutoLoad:"自動載入更多圖片",
    galleryLoadAll:"載入更多圖片時自動處理全部頁",
    galleryLoadAllTip:"若頁數過多可能影響體驗",
    galleryDownloadWithZip:"下載所有時打包成zip",
    galleryDownloadWithZipAlert:"正在打包，請耐心等候數十秒",
    galleryScaleSmallSize1:"實際尺寸的高和寬都小於 ",
    galleryScaleSmallSize2:" 像素則歸入小尺寸圖片",
    galleryShowSmallSize:"默認顯示小尺寸圖片",
    galleryTransition:"顯示圖庫切換圖片的特效",
    gallerySidebarPosition:"縮略圖欄位置",
    bottom:'底部',
    right:'右側',
    left:'左側',
    top:'頂部',
    gallerySidebarSize:"高度",
    gallerySidebarSizeTip:"縮略圖欄的高（如果是水平放置）或者寬（如果是垂直放置）",
    galleryMax1:"最多預讀 ",
    galleryMax2:" 張圖片（前後各多少張）",
    galleryAutoZoom:"縮放改回 100%（chrome）",
    galleryAutoZoomTip:"如果有放大，則把圖片及 sidebar 部分的縮放改回 100%，增大可視面積（僅在 chrome 下有效）",
    galleryDescriptionLength1:"注釋的最大寬度",
    galleryDescriptionLength2:" 個字元",
    galleryAutoOpenSites:"自動打開圖庫的網址正則，一行一條，若前綴@則自動展開圖庫",
    autoOpenViewmore:"打開圖庫時自動展開",
    galleryViewmoreLayout:"圖庫展開之後的佈局",
    gallerySearchData:"搜圖站點設置，清空還原",
    galleryEditSite:"在線編輯站點",
    imgWindow:"圖片窗口",
    imgWindowFitToScreen:"適應屏幕，並且水平垂直居中",
    imgWindowFitToScreenTip:"適應方式為contain，非cover",
    imgWindowDefaultTool:"打開窗口時默認選擇的工具",
    hand:'抓手',
    rotate:'旋轉',
    zoom:'放大鏡',
    imgWindowEscKey:"Esc鍵關閉",
    imgWindowDblClickImgWindow:"雙擊圖片窗口關閉",
    imgWindowClickOutside:"點擊圖片外部關閉（覆蓋層）",
    imgWindowClickOutsideTip:"僅當覆蓋層顯示時生效",
    none:'無',
    click:'單擊',
    dblclick:'雙擊',
    imgWindowOverlayerShown:"覆蓋層",
    imgWindowOverlayerColor:"顏色和不透明度",
    imgWindowShiftRotateStep1:"旋轉時，按住shift鍵，旋轉的步進",
    imgWindowShiftRotateStep2:" 度",
    imgWindowMouseWheelZoom:"滾輪縮放",
    imgWindowZoomRange:"滾輪縮放比例",
    imgWindowZoomRangeTip:"縮放比例(必須為正數)",
    others:"其它",
    waitImgLoad:"等圖片完全載入後，才開始執行彈出放大等操作",
    waitImgLoadTip:"按住ctrl鍵的時候,可以臨時執行和這個設定相反的設定",
    debug:"調試模式",
    customRules:"自定義大圖規則",
    firstEngine:"首選搜圖引擎",
    refreshWhenError:"讀取錯誤，點擊重載",
    switchSlide:"開關側邊欄",
    viewmore:"展開更多",
    countDown:"倒計時",
    customLang:"設定語言",
    defaultLang:"自動選擇",
    toggleIcon:"隱藏圖標",
    initShow:"反轉快捷鍵，默認顯示預覽",
    stayOut:"使浮動工具欄顯示在圖片外部"
};
var ptLang={
    //Português by AstroCoelestis.
    saveBtn: "Salvar",
    download:"Baixar",
    saveBtnTips: "algumas opções precisam atualizar a página para entrar em vigor",
    closeBtn: "Cancelar",
    invertBtn:"Inverter Seleção",
    closeBtnTips: "cancela esta configuração e restaura todas as opções",
    resetLink: "Restaurar definições originais",
    resetLinkTips: "restaura todas as configurações para os valores padrão",
    share:"Compartilhar",
    suitLongImg:"Adaptar imagens longas na janela de rolagem",
    globalkeys:"Atalhos globais para visualização: ",
    globalkeysPress:"Pressionar para alternar a visualização",
    globalkeysHold:"Segurar para ativar a visualização",
    globalkeysType:"Método para ativar a visualização",
    loadAll:"Carregar mais páginas",
    loadedAll:"Carregamento concluído",
    loading:"Carregando...",
    loadAllTip:"Carregar a imagem em uma nova aba",
    viewmoreEndless:"Rolar até o final no modo ver mais carrega automaticamente a próxima página",
    fiddle:"Operar",
    fiddleTip:"Imagens em pop-up para operações complexas",
    closeFirst:"Fechar a Galeria existente primeiro",
    collect:"Coleção",
    collected:"Foi colecionado",
    exitCollection:"Sair da coleção",
    exitCollectionTip:"Clique para sair do modo de coleção",
    noCollectionYet:"Você não tem nenhuma imagem na coleção",
    collectDetail:"Descrição",
    collectDetailTip:"Adicione algumas descrições às suas imagens favoritas",
    playSlide:"Reproduzir apresentação de slides",
    slideGap:"Intervalo (s)",
    slideGapTip:"Intervalo, unidade (segundos)",
    slideBack:"Voltar",
    slideBackTip:"Reproduzir de trás pra frente",
    slideWait:"Aguarde a leitura da imagem",
    slideWaitTip:"A contagem regressiva começa depois que cada imagem é lida completamente.",
    slideSkipError:"Pular imagens com erro",
    slideSkipErrorTip:"Pule rapidamente para ler as imagens com erro",
    type:"Categoria",
    typeTip:"Selecione a categoria da imagem",
    advancedRules:"Regras Avançadas",
    advancedRulesTip:"Combinado por regras avançadas",
    tpRules:"Regras curinga",
    tpRulesTip:"Combinado por regras curinga",
    scaleRules:"Ampliado",
    scaleRulesTip:"A imagem encontrada automaticamente, mas dimensionada",
    noScaleRules:"Sem dimensionamento",
    noScaleRulesTip:"A imagem encontrada automaticamente, mas não dimensionada",
    smallRules:"Tamanho pequeno",
    smallRulesTip:"Imagem de tamanho pequeno, o tamanho real da altura e largura são menores que #t# pixels",
    lockSizeTip:"Bloquear tamanho máximo",
    command:"Comando",
    commandTip:"Menu de Comando",
    onlineEdit:"Edição on-line",
    onlineEditTip:"Edite esta imagem online usando #t#",
    openInNewWindow:"Abrir em nova janela",
    openInNewWindowTip:"Abrir imagem em nova janela",
    findInPage:"Localizar na página",
    findInPageTip:"Role até a imagem atual na página",
    viewCollection:"Ver coleção",
    viewCollectionTip:"Veja todas as imagens colecionadas",
    inCollection:"Não é possível usar no modo Coleção",
    cantFind:"A imagem não está no documento ou está oculta e não pode ser localizada!",
    exportImages:"Exportar todas as imagens",
    exportImagesTip:"Exportar todas as imagens exibidas de tamanho grande em uma nova janela",
    downloadImage:"Baixar todas as exibidas",
    downloadImageTip:"Baixar as imagens exibidas atualmente",
    copyImagesUrl:"Copiar todos os URLs das imagens",
    copyImagesUrlTip:"Copiar todos os URLs das imagens de tamanho grande exibidas",
    copySuccess:"#t# URLs copiados com sucesso",
    autoRefresh:"Carregar automaticamente a página",
    autoRefreshTip:"Quando as últimas imagens forem visualizadas, role a janela para baixo, para que uma página carregue as novas imagens",
    enterFullsc:"Entrar em tela cheia",
    exitFullsc:"Sair da tela cheia",
    config:"Configurações",
    openConfig:"Abrir configurações",
    closeGallery:"Fechar a Galeria",
    returnToGallery:"Voltar para a Galeria",
    picInfo:"Clique para mudar",
    picNote:"Anotação de imagem",
    urlFilter:"filtrar links",
    urlFilterTip:"Insira palavras-chave ou expressões regulares para filtrar links",
    resolution:"Resolução da imagem",
    scaleRatio:"Relação de escala",
    similarImage:"Pesquisando por imagem",
    scale:"Ampliar",
    horizontalFlip:"Giro horizontal",
    verticalFlip:"Giro vertical",
    actualBtn:"Visualizar original (A)",
    searchBtn:"Procurar a imagem original (S)",
    galleryBtn:"Visualizar a galeria (G)",
    currentBtn:"Visualizar atual (C)",
    magnifierBtn:"Lupa / Ampliar (M)",
    picTitle:"Título da imagem",
    picNum:"Número de imagens",
    picTips:"Ver imagens com a tecla CTRL",
    savePageTips:"Salvar essa página para baixar todas as imagens",
    exportImagesUrl:"Exportar URL da imagem",
    exportImagesUrlPop:"Ctrl+C para copiar o URL da imagem",
    beginSearchImg:"#t# inicia a procupa por imagem...",
    findNoPic:"A imagem original não foi encontrada",
    findOverBeginLoad:"#t# fim do mapa, encontradas #t# imagens correspondentes, carregando a primeira",
    loadNextSimilar:"A imagem original falhou ao carregar, tentando carregar o próximo resultado...",
    loadError:"Falha ao carregar",
    openHomePage:"Abrir página inicial",
    position:"Posição da tela",
    positionTips:"Segure ALT para ocultar",
    topLeft:"O canto superior esquerdo da imagem",
    topRight:"O canto superior direito da imagem",
    bottomRight:"O canto inferior direito da imagem",
    bottomLeft:"O canto inferior esquerdo da imagem",
    topCenter:"Ao lado da foto",
    bottomCenter:"Abaixo da imagem",
    floatBar:"ícones",
    showDelay:"Mostrar atraso",
    ms:"ms",
    hide:"Ocultar",
    hideDelay:"Ocultar atraso",
    forceShow:"Mostrar a barra de ferramentas sobre imagem sem ampliação além desse tamanho, ",
    forceShowTip:"Mostrar a barra de ferramentas flutuante quando o tamanho da imagem não dimensionada exceder o tamanho definido abaixo",
    sizeLimitOr:"Afetado apenas por altura OU largura",
    px:"px",
    minSizeLimit:"Mostrar barra de ferramentas sobre a imagem ampliada além desse tamanho",
    minSizeLimitTip:"Depois que a imagem é dimensionada (o tamanho original da imagem não corresponde ao tamanho real), a barra de ferramentas flutuante é exibida quando o comprimento da imagem mostrada é maior que o valor definido.",
    defaultSizeLimit:"Limite de tamanho padrão para a Galeria",
    listenBg:"Observar imagem de fundo",
    listenBgTip:"Mostra a barra de ferramentas em um elemento com uma imagem de fundo",
    butonOrder:"Tipo de ícones da barra de ferramentas",
    keysEnable:"Ativar atalhos",
    keysActual:"Abrir a imagem grande",
    keysActualTip:"Pressione este botão para abrir uma imagem grande quando a barra flutuante aparecer",
    keysSearch:"Encontre a imagem original",
    keysSearchTip:"Pressione este botão para encontrar a imagem original quando a barra flutuante aparecer",
    headSearchTip:"Pesquisar por imagem",
    headSearchAll:"Pesquisar todas",
    keysCurrent:"Abrir a imagem atual",
    keysCurrentTip:"Pressione este botão para abrir a imagem atual quando a barra flutuante aparecer",
    keysMagnifier:"Abrir a lupa para observar",
    keysMagnifierTip:"Pressione este botão para abrir a lupa quando a barra flutuante aparecer",
    keysGallery:"Abrir a Galeria（Global com funcKeys）",
    keysGalleryTip:"Pressione este botão para abrir a Galeria quando a barra flutuante aparecer",
    openGallery:"Abrir a Galeria",
    magnifier:"Ampliar",
    magnifierRadius:"Raio padrão",
    magnifierWheelZoomEnabled:"Ativar ampliação da roda",
    magnifierWheelZoomRange:"Taxa de ampliação da lupa",
    gallery:"Galeria",
    galleryFitToScreen:"Dimensionar a imagem para caber na tela",
    galleryFitToScreenSmall:"Dimensionar a imagem pequena também",
    galleryFitToScreenTip:"Adaptar para conter, não cobrir",
    galleryScrollEndToChange:"Alterne a imagem depois que a imagem longa rolar até o final",
    galleryScrollEndToChangeTip:"Válido após cancelar a opção anterior",
    galleryExportType:"Tipo padrão quando as imagens são exportadas",
    grid:"Classificação de blocos",
    gridBig:"classificação original",
    list:"Classificação da lista",
    galleryAutoLoad:"Carregar automaticamente mais imagens na próxima página",
    galleryLoadAll:"Processe automaticamente todas as páginas ao carregar mais imagens",
    galleryLoadAllTip:"Muitas páginas podem afetar a experiência",
    galleryDownloadWithZip:"Compactar para ZIP quando baixar tudo",
    galleryDownloadWithZipAlert:"Comprimindo, espere um pouco por favor",
    galleryScaleSmallSize1:"O tamanho real é menor que a altura e a largura",
    galleryScaleSmallSize2:"Os pixels são agrupados em imagens de tamanho pequeno",
    galleryShowSmallSize:"Mostrar imagens de tamanho pequeno por padrão",
    galleryTransition:"Mostrar efeitos ao alternar a galeria",
    gallerySidebarPosition:"Posição da barra de miniaturas",
    bottom:"Inferior",
    right:"Direita",
    left:"Esquerda",
    top:"Superior",
    gallerySidebarSize:"Altura",
    gallerySidebarSizeTip:"A altura da barra de miniaturas (se for horizontal) ou a largura (se for vertical)",
    galleryMax1:"Pré-busca máxima",
    galleryMax2:"Imagens (antes e depois)",
    galleryAutoZoom:"Ampliação volta para 100% (chrome)",
    galleryAutoZoomTip:"Se você ampliar, altera o zoom das seções da imagem e da barra lateral de volta para 100% e aumenta a área visível (válido apenas no chrome)",
    galleryDescriptionLength1:"O máximo de anotação é",
    galleryDescriptionLength2:"Caracteres",
    galleryAutoOpenSites:"Frequências de URLs para galeria automaticamente aberta, começam com @ para Ver Mais, um por linha",
    autoOpenViewmore:"Expandir automaticamente ao abrir a galeria",
    galleryViewmoreLayout:"O layout após a galeria ser expandida",
    gallerySearchData:"Regras do site para pesquisa, esvazie-o para restaurar",
    galleryEditSite:"Site de edição online",
    imgWindow:"Janela",
    imgWindowFitToScreen:"Adaptar à tela",
    imgWindowFitToScreenTip:"Adaptar para conter, não cobrir",
    imgWindowDefaultTool:"A ferramenta selecionada por padrão ao abrir a janela",
    hand:"Mão",
    rotate:"Girar",
    zoom:"Lupa",
    imgWindowEscKey:"Tecla Esc para fechar",
    imgWindowDblClickImgWindow:"Clique duplo para fechar",
    imgWindowClickOutside:"Clique na sobreposição para fechar",
    imgWindowClickOutsideTip:"Ativo apenas quando a Sobreposição for exibida",
    none:"Nenhum",
    click:"Clique",
    dblclick:"Clique duplo",
    imgWindowOverlayerShown:"Sobreposição",
    imgWindowOverlayerColor:"Cor e Opacidade",
    imgWindowShiftRotateStep1:"Gira ao pressionar a tecla Shift em cada ",
    imgWindowShiftRotateStep2:"Grau",
    imgWindowMouseWheelZoom:"Ampliação da roda do mouse",
    imgWindowZoomRange:"Alcance da ampliação",
    imgWindowZoomRangeTip:"Taxa de ampliação (precisa ser positiva)",
    others:"Outros",
    waitImgLoad:"Começar a realizar operações como ampliar quando a imagem é carregada",
    waitImgLoadTip:"Ao manter pressionada a tecla Ctrl, você pode executar temporariamente o oposto à esta configuração",
    debug:"Modo de depuração",
    customRules:"Regras personalizadas para imagem grande",
    firstEngine:"Motor de busca preferido (primeiro)",
    refreshWhenError:"Erro de leitura, clique para sobrecarregar",
    switchSlide:"Alternar barra lateral",
    viewmore:"Ver mais",
    countDown:"Contagem regressiva",
    customLang:"Definir idioma",
    defaultLang:"Auto",
    toggleIcon:"ícone de alternância",
    initShow:"Inverter atalho para mostrar a visualização por padrão",
    stayOut:"Deixe a barra flutuante ficar fora da imagem"
};
var ruLang={
    //Русский перевод by RX-3200 и vanja-san.
    saveBtn: "OK",
    download:"Скачать",
    saveBtnTips: "Некоторые параметры требуют обновления страницы, чтобы применить изменения",
    closeBtn: "Отмена",
    invertBtn:"Инвертировать",
    closeBtnTips: "Отменить и восстановить все параметры",
    resetLink: "Восстановить настройки по умолчанию",
    resetLinkTips: "Восстановить все настройки до стандартных значений",
    share: "Поделиться",
    suitLongImg: "Окно прокрутки подходит для длинных изображений",
    globalkeys:"Глобальные клавиши для предпросмотра: ",
    globalkeysPress:"Нажать: переключить предпросмотр",
    globalkeysHold:"Удерживать: включить предпросмотр",
    globalkeysType:"Способ активации предпросмотра",
    loadAll:"Загрузить больше страниц",
    loadedAll:"Загрузка завершена",
    loading:"Загрузка...",
    loadAllTip:"Загружать изображение на следующей странице",
    viewmoreEndless:"Загружать больше изображений в режиме просмотра при прокрутке вниз",
    fiddle:"Оперировать",
    fiddleTip:"Всплывающие изображения для сложных операций",
    closeFirst:"Сначала закройте существующую галерею",
    collect:"Коллекция",
    collected:"Было получено",
    exitCollection:"Выйти из коллекции",
    exitCollectionTip:"Нажмите, чтобы выйти из режима коллекционирования",
    noCollectionYet:"У вас нет картинок в коллекции",
    collectDetail:"Описание",
    collectDetailTip:"Добавьте описания к своим избранным изображениям",
    playSlide:"Запустить слайд-шоу",
    slideGap:"Интервал (сек)",
    slideGapTip:"Интервал, единица измерения (секунды)",
    slideBack:"Назад",
    slideBackTip:"Запускать с последней к первой",
    slideWait:"Дождитесь считывания изображения",
    slideWaitTip:"Отсчёт начинается после полного считывания каждого изображения.",
    slideSkipError:"Пропускать изображения с ошибками",
    slideSkipErrorTip:"Быстро пропускать считывание изображений с ошибками",
    type:"Категория",
    typeTip:"Выберите категорию изображения",
    advancedRules:"Расширенные правила",
    advancedRulesTip:"Соответствие расширенным правилам",
    tpRules:"Правила подстановочных знаков",
    tpRulesTip:"Соответствие правилам подстановочных знаков",
    scaleRules:"Увеличено",
    scaleRulesTip:"Изображение, которое находится автоматически, но масштабируется",
    noScaleRules:"Без масштабирования",
    noScaleRulesTip:"Изображение, которое находится автоматически, но не масштабируется",
    smallRules:"Небольшой размер",
    smallRulesTip:"Изображение небольшого размера, фактический размер высоты и ширины менее #t# пикселей",
    lockSizeTip:"Заблокировать максимальный размер",
    command:"Команда",
    commandTip:"Меню команд",
    onlineEdit:"Онлайн редактирование",
    onlineEditTip:"Отредактируйте это изображение онлайн, используя #t#",
    openInNewWindow:"Открыть в новом окне",
    openInNewWindowTip:"Открыть изображение в новом окне",
    findInPage:"Найти на странице",
    findInPageTip:"Прокрутка до текущего изображения на странице",
    viewCollection:"Посмотреть коллекцию",
    viewCollectionTip:"Посмотреть все изображения в коллекции",
    inCollection:"Невозможно использовать в режиме коллекции",
    cantFind:"Изображения нет в документе, или оно скрыто и не может быть найдено!",
    exportImages:"Экспорт всех изображений",
    exportImagesTip:"Экспорт всех показанных изображений большого размера в новое окно",
    downloadImage:"Скачать всё показанное",
    downloadImageTip:"Скачайте текущие показанные картинки",
    copyImagesUrl:"Скопировать URL всех изображений",
    copyImagesUrlTip:"Скопируйте все показанные URL-адреса изображений большого размера",
    copySuccess:"URL #t# скопирован успешно",
    autoRefresh:"Автозагрузка страницы",
    autoRefreshTip:"Когда последние несколько изображений будут просмотрены, прокрутите окно вниз, чтобы на веб-странице загрузились новые изображения",
    enterFullsc:"Войти в полноэкранный режим",
    exitFullsc:"Выйти из полноэкранного режима",
    config:"Настройки",
    openConfig:"Настройки",
    closeGallery:"Закрыть галлерею",
    returnToGallery:"Вернуться в галерею",
    picInfo:"Нажмите, чтобы изменить",
    picNote:"Аннотация изображения",
    urlFilter:"Фильтр URL-адресов",
    urlFilterTip:"Введите ключевые слова или регулярное выражение для фильтрации URL-адресов.",
    resolution:"Разрешение изображения",
    picNum:"Количество изображений",
    picTips:"Просмотр изображения с помощью клавиши CTRL",
    savePageTips:"Сохраните эту страницу, чтобы скачать все изображения",
    scaleRatio:"Коэффициент масштабирования",
    similarImage:"Поиск по изображению",
    scale:"Масштаб",
    horizontalFlip:"Повернуть по горизонтали",
    verticalFlip:"Повернуть по вертикали",
    actualBtn:"Посмотреть оригинал (A)",
    searchBtn:"Найти оригинальное изображение (S)",
    galleryBtn:"Посмотреть галерею (G)",
    currentBtn:"Посмотреть текущее (C)",
    magnifierBtn:"Экранная лупа / Зум (M)",
    picTitle:"Название изображения",
    exportImagesUrl:"Экспорт изображения по URL",
    exportImagesUrlPop:"Ctrl+C: скопировать URL изображения",
    beginSearchImg:"#t# поиск изображения...",
    findNoPic:"Оригинальное изображение не найдено",
    findOverBeginLoad:"#t# конец карты, найдите #t# подходящие изображения, начните загрузку первой",
    loadNextSimilar:"Оригинальное изображение не удалось загрузить, попробуйте загрузить следующий результат...",
    loadError:"Невозможно загрузить",
    openHomePage:"Открыть домашнюю страницу",
    position:"Положение отображения",
    positionTips:"Удерживайте ALT: скрыть",
    topLeft:"Верхний левый угол изображения",
    topRight:"Верхний правый угол изображения",
    bottomRight:"Нижний правый угол изображения",
    bottomLeft:"Нижний левый угол изображения",
    topCenter:"Рядом с изображением",
    bottomCenter:"Под изображением",
    floatBar:"Панель инструментов",
    showDelay:"Задержка до отображения",
    ms:"мс",
    hide:"Скрыть",
    hideDelay:"Задержка до скрытия",
    forceShow:"Показывать панель инструментов на немасштабированном изображении сверх указанного размера, ",
    forceShowTip:"Показывать плавающую панель инструментов, когда размер немасштабированного изображения превышает размер, установленный ниже",
    sizeLimitOr:"Влияет только от высоты ИЛИ ширины",
    px:"пикс",
    minSizeLimit:"Показывать панель инструментов над увеличенным изображением, превышающим указанный размер",
    minSizeLimitTip:"После масштабирования изображения (исходный размер изображения не соответствует фактическому размеру) плавающая панель инструментов отображается, когда отображаемая длина изображения превышает установленное значение.",
    defaultSizeLimit:"Ограничение размера для галереи по умолчанию",
    listenBg:"Фоновое изображение для прослушивания",
    listenBgTip:"Показывать панель инструментов на элементе с фоновым изображением",
    butonOrder:"Сортировка значков панели инструментов",
    keysEnable:"Включить ярлыки",
    keysActual:"Открыть большое изображение",
    keysActualTip:"Нажмите эту кнопку, чтобы открыть большое изображение при появлении плавающей панели",
    keysSearch:"Найти оригинальное изображение",
    keysSearchTip:"Нажмите эту кнопку, чтобы найти оригинальное изображение, когда появляется плавающая панель",
    headSearchTip:"Искать по изображению",
    headSearchAll:"Искать все",
    keysCurrent:"Открыть текущее изображение",
    keysCurrentTip:"Нажмите эту кнопку, чтобы открыть текущее изображение при появлении плавающей панели",
    keysMagnifier:"Открыть лупу, чтобы рассмотреть",
    keysMagnifierTip:"Нажмите эту кнопку, чтобы открыть лупу при появлении плавающей панели",
    keysGallery:"Открыть галерею（Глобально с funcKeys）",
    keysGalleryTip:"Нажмите эту кнопку, чтобы открыть галерею при появлении плавающей панели",
    openGallery:"Открыть галерею",
    magnifier:"Масштаб",
    magnifierRadius:"Радиус по умолчанию",
    magnifierWheelZoomEnabled:"Включить масштабирование колёсиком",
    magnifierWheelZoomRange:"Коэффициент увеличения для лупы",
    gallery:"Галерея",
    galleryFitToScreen:"Масштабировать изображение, чтобы оно соответствовало размеру экрана",
    galleryFitToScreenSmall:"Также масштабировать небольшое изображение",
    galleryFitToScreenTip:"Адаптироваться для сдерживания, не обложку",
    galleryScrollEndToChange:"Переключать изображение после прокрутки длинного изображения до конца",
    galleryScrollEndToChangeTip:"Действует после отмены предыдущего параметра",
    galleryExportType:"Сортировка по умолчанию при экспорте изображений",
    grid:"Соритровка плиткой",
    gridBig:"Сортировка по оригиналу",
    list:"Сортировка списком",
    galleryAutoLoad:"Автозагружать больше изображений на следующей странице",
    galleryLoadAll:"Автообрабатывать все страницы при загрузке больше изображений",
    galleryLoadAllTip:"Слишком много страниц может повлиять на взаимодействие",
    galleryDownloadWithZip:"Сжимать в ZIP при скачивании всех",
    galleryDownloadWithZipAlert:"Сжатие, подождите...",
    galleryScaleSmallSize1:"Фактический размер меньше, чем высота и ширина",
    galleryScaleSmallSize2:"Пиксели группируются в изображения небольшого размера",
    galleryShowSmallSize:"По умолчанию показывать изображения небольшого размера",
    galleryTransition:"Показывать эффекты при переключении галереи",
    gallerySidebarPosition:"Положение панели миниатюр",
    bottom:"Снизу",
    right:"Справа",
    left:"Слева",
    top:"Сверху",
    gallerySidebarSize:"Высота",
    gallerySidebarSizeTip:"Высота панели миниатюр (если она горизонтальная) или ширина (если она вертикальная)",
    galleryMax1:"Максимальная предварительная выборка",
    galleryMax2:"Изображения (до и после)",
    galleryAutoZoom:"Возвращать масштаб к 100% (Chrome)",
    galleryAutoZoomTip:"Если вы увеличиваете масштаб, измените масштаб изображения и разделов боковой панели обратно на 100% и увеличьте видимую область (действительно только в Chrome)",
    galleryDescriptionLength1:"Максимум аннотаций",
    galleryDescriptionLength2:"Символов",
    galleryAutoOpenSites:"Обычные URL-адреса для автооткрытия галереи, по одному в строке, начинаются с @ для «Посмотреть больше»",
    autoOpenViewmore:"Автопросмотр дополнительной информации при открытии галереи",
    galleryViewmoreLayout:"Режим макета «Посмотреть больше»",
    gallerySearchData:"Правила сайта для поиска, очистите его, чтобы восстановить",
    galleryEditSite:"Сайт онлайн-редактирования",
    imgWindow:"Окно изображения",
    imgWindowFitToScreen:"Адаптировать к экрану",
    imgWindowFitToScreenTip:"Адаптировать, чтобы сдерживать, не обложка",
    imgWindowDefaultTool:"Инструмент, выбранный по умолчанию при открытии окна",
    hand:"Рука",
    rotate:"Поворот",
    zoom:"Лупа",
    imgWindowEscKey:"Esc: закрыть",
    imgWindowDblClickImgWindow:"Дважды нажмите, чтобы закрыть",
    imgWindowClickOutside:"Нажмите на слой, чтобы закрыть",
    imgWindowClickOutsideTip:"Включить только при отображении оверлея",
    none:"Ничего",
    click:"Нажатие",
    dblclick:"Двойное нажатие",
    imgWindowOverlayerShown:"Оверлей",
    imgWindowOverlayerColor:"Цвет и непрозрачность",
    imgWindowShiftRotateStep1:"Поворот при удержании клавиши Shift на каждом ",
    imgWindowShiftRotateStep2:"Степень",
    imgWindowMouseWheelZoom:"Масштаб колёсиком мыши",
    imgWindowZoomRange:"Диапазон масштабирования",
    imgWindowZoomRangeTip:"Коэффициент масштабирования (должен быть положительным)",
    others:"Другое",
    waitImgLoad:"Начните выполнять такие операции, как масштабирование, пока изображение не загрузится.",
    waitImgLoadTip:"Удерживая клавишу Ctrl, можно временно выполнить противоположные этой настройке действия",
    debug:"Режим отладки",
    customRules:"Пользовательские правила для больших изображений",
    firstEngine:"Предпочитаемая (первая) поисковая система",
    refreshWhenError:"Ошибка считывания, нажмите для перегрузки",
    switchSlide:"Переключить боковую панель",
    viewmore:"Посмотреть больше",
    countDown:"Обратный отсчёт",
    customLang:"Пользовательский язык",
    defaultLang:"Автоопределение",
    toggleIcon:"Переключение иконки",
    initShow:"Инвертировать ярлык, чтобы по умолчанию показывать предпросмотр",
    stayOut:"Плавающая панель за пределами изображения"
};
var langList={
    'en': "English",
    'pt': "Português",
    'ru': "Русский",
    'zh-CN': "简体中文",
    'zh-TW': "正體中文"
}
var i18nData={};
function setLang(la){
    switch (la){
        case "zh-CN":
        case "zh-SG":
            i18nData=zhCNLang;
            break;
        case "zh-TW":
        case "zh-HK":
        case "zh-MO":
            i18nData=zhTWLang;
            break;
        case "pt":
        case "pt-BR":
            i18nData=ptLang;
            break;
        case "ru":
        case "ru-RU":
            i18nData=ruLang;
            break;
        default:
            i18nData=defaultLang;
            break;
    }
}
