const langData = [
{
    name: "English",
    match: ["en"],
    lang: {
        //English by RX-3200.
        saveBtn: "OK",
        saveName: "Save name",
        saveNameTip: "Save images with the name",
        default: "Default",
        textFirst: "Info first if exist",
        onlyUrl: "Only with URL",
        urlAndText: "URL + Info",
        download: "Download",
        saveBtnTips: "some options need to refresh the page to take effect",
        additionalFeature: "Additional feature, take effect when altkey is pressed",
        invertAdditionalFeature: "Invert shortcut keys, use additional features by default",
        copy: "Copy link",
        copyImg: "Copy image data",
        openInNewTab: "Open in New Tab",
        closeBtn: "Cancel",
        invertBtn: "Invert",
        compareBtn: "Compare",
        closeBtnTips: "cancel this setting and restore all options",
        resetLink: "Restore default settings",
        resetLinkTips: "restore all settings to default values",
        share: "Share",
        suitLongImg: "Suit long pics in scroll window",
        globalkeys: "Global keys for preview: ",
        globalkeysPress: "Press to toggle preview",
        globalkeysHold: "Hold to enable preview",
        globalkeysType: "Method to enable preview",
        closeAfterPreview: "Close the picture window after preview",
        loadAll: "Load more pages",
        loadedAll: "Load completed",
        loading: "Loading ...",
        loadAllTip: "Load the picture on the next page",
        viewmoreEndless: "Load more pics in viewmore when scroll to bottom",
        fiddle: "Operate",
        fiddleTip: "Pop-up pictures for complex operations",
        addImageUrls: "Add image",
        addImageUrlsTips: "Add more images via url",
        closeFirst: "Close the existing Gallery first",
        collect: "Collection",
        collected: "Has been collected",
        exitCollection: "Exit collection",
        exitCollectionTip: "Click to exit the collection mode",
        noCollectionYet: "You have no picture in the collection",
        collectDetail: "Description",
        collectDetailTip: "Add some descriptions to your favorite pictures",
        playSlide: "Play slideshow",
        slideGap: "Interval (s)",
        slideGapTip: "Interval, unit (seconds)",
        slideBack: "Back",
        slideBackTip: "Play from back to front",
        slideWait: "Wait for image reading",
        slideWaitTip: "The countdown starts after each image is completely read.",
        slideSkipError: "Skip error pictures",
        slideSkipErrorTip: "Quickly skip to read the error pictures",
        type: "Category",
        typeTip: "Select image category",
        showWithRules: "Force show icon with rule",
        showWithRulesTip: "Show icon if the image matched rules no matter which size it is",
        advancedRules: "Advanced Rules",
        advancedRulesTip: "Matched by advanced rules",
        tpRules: "Wildcard rules",
        tpRulesTip: "Matched by wildcard rules",
        scaleRules: "Zoomed",
        scaleRulesTip: "The image which is finded automatically but scaled",
        noScaleRules: "No scaling",
        noScaleRulesTip: "The image which is finded automatically but without scale",
        smallRules: "Small size",
        smallRulesTip: "Small size image, the actual size of the height and width are less than #t# pixels",
        lockSizeTip: "Lock the max size",
        command: "Command",
        commandTip: "Command Menu",
        onlineEdit: "Online editing",
        onlineEditTip: "Edit this image online using #t#",
        openInNewWindow: "Open in new window",
        openInNewWindowTip: "Open image in new window",
        findInPage: "Find In Page",
        findInPageTip: "Scroll to the current image in page",
        viewCollection: "View Collection",
        viewCollectionTip: "View all collected images",
        inCollection: "Unable to use in Collection mode",
        cantFind: "The image is not in the document, or it is hidden and cannot be located!",
        exportImages: "Export all Images",
        exportImagesTip: "Export all shown big size images to new window",
        downloadImage: "Download all shown",
        downloadImageTip: "Download the current shown pictures",
        copyImagesUrl: "Copy all images Urls",
        copyImagesUrlTip: "Copy all shown big size image Urls",
        copySuccess: "Copied #t# Urls successfully",
        autoRefresh: "Auto load page",
        autoRefreshTip: "When the last few images are viewed, scroll the window to the bottom, so that some webpage will load the new images",
        enterFullsc: "Enter full screen",
        exitFullsc: "Exit full screen",
        config: "Settings",
        openConfig: "Open Settings",
        closeGallery: "Close Gallery",
        returnToGallery: "Back to the Gallery",
        picInfo: "Click to change",
        picNote: "Img annotation",
        urlFilter: "Url filter",
        urlFilterTip: "Input key words or Regexp to filter Urls",
        resolution: "Img Resolution",
        picNum: "Number of pictures",
        picTips: "View pictures with CTRL key",
        savePageTips: "Save this page to download all pics",
        scaleRatio: "Scaling ratio",
        similarImage: "Searching by image",
        scale: "Zoom",
        horizontalFlip: "Horizontal flip",
        verticalFlip: "Vertical flip",
        actualBtn: "View original (A)",
        searchBtn: "Find the original image (S)",
        galleryBtn: "View gallery (G)",
        currentBtn: "View current (C)",
        magnifierBtn: "Magnifier / ZooM (M)",
        picTitle: "Picture Title",
        exportImagesUrl: "Export image Url",
        exportImagesUrlPop: "Ctrl+C to copy image Url",
        beginSearchImg: "#t# begin Search Img ...",
        findNoPic: "The original image was not found",
        findOverBeginLoad: "#t# end of the map, find #t# matching pictures, start loading the first one",
        loadNextSimilar: "The original image failed to load, try to load the next result...",
        loadError: "Load failed",
        openHomePage: "Open Home page",
        position: "Display position",
        positionTips: "Hold ALT to hide",
        topLeft: "The top left corner of the picture",
        topRight: "The top right corner of the picture",
        bottomRight: "The bottom right corner of the picture",
        bottomLeft: "The bottom left corner of the picture",
        topCenter: "Beside the picture",
        bottomCenter: "Below the picture",
        floatBar: "Toolbar",
        previewFollowMouse: "Show preview beside mouse",
        showDelay: "Show delay",
        ms: "ms",
        hide: "Hide",
        hideDelay: "Hide delay",
        forceShow: "Show toolbar over Non-zoomed image beyond that size, ",
        forceShowTip: "Show floating toolbar when non-scaled image size exceeds the size set below",
        sizeLimitOr: "Effected by height OR width only",
        px: "px",
        minSizeLimit: "Show toolbar over Zoomed image beyond that size",
        minSizeLimitTip: "After the image is scaled (the original size of the image does not match the actual size), the floating toolbar is displayed when the shown image length is greater than the set value.",
        defaultSizeLimit: "Default size limit for gallery",
        listenBg: "Listening background image",
        backgroundColor: "Background Color",
        listenBgTip: "Show toolbar on the element with the background image",
        butonOrder: "Sort of toolbar icons",
        keysEnable: "Enable shortcuts",
        keysActual: "Open the big picture",
        keysActualTip: "Press this button to open a large image when floating bar appears",
        keysSearch: "Find the original image",
        keysSearchTip: "Press this button to find the original image when floating bar appears",
        headSearchTip: "Search by image",
        headSearchAll: "Search All",
        keysCurrent: "Open the current picture",
        keysCurrentTip: "Press this button to open the current image when floating bar appears",
        keysMagnifier: "Open the magnifier to observe",
        keysMagnifierTip: "Press this button to open the magnifier when floating bar appears",
        keysGallery: "Open Gallery（Global with funcKeys）",
        keysGalleryTip: "Press this button to open the Gallery when floating bar appears",
        openGallery: "Open Gallery",
        magnifier: "Zoom",
        magnifierRadius: "Default radius",
        magnifierWheelZoomEnabled: "Enable wheel zoom",
        magnifierWheelZoomRange: "Zoom ratio for magnifier",
        gallery: "Gallery",
        galleryFitToScreen: "Scale the image to fit the screen",
        galleryFitToScreenSmall: "Scale the small image also",
        galleryFitToScreenTip: "Adapt to be contain, not cover",
        galleryScrollEndToChange: "Switch the image after the long picture scrolls to the end",
        galleryScrollEndToChangeTip: "Valid after canceling the previous option",
        galleryExportType: "Default sort when images exported",
        grid: "Tile sorting",
        gridBig: "original sorting",
        list: "List sorting",
        galleryAutoLoad: "Automatically load more images on next page",
        galleryLoadAll: "Automatically process all pages when loading more images",
        galleryLoadAllTip: "Too many pages may affect the experience",
        galleryDownloadWithZip: "Compress to ZIP when download all",
        galleryDownloadWithZipAlert: "Compressing, wait for a while please",
        galleryScaleSmallSize1: "The actual size is less than the height and width",
        galleryScaleSmallSize2: "Pixels are grouped into small size images",
        galleryShowSmallSize: "Show small size pictures by default",
        galleryTransition: "Show effects when gallery switch",
        gallerySidebarPosition: "Thumbnail bar position",
        bottom: "Bottom",
        right: "Right",
        left: "Left",
        top: "Top",
        gallerySidebarSize: "Height",
        gallerySidebarSizeTip: "The height of the thumbnail bar (if it is horizontal) or the width (if it is vertical)",
        galleryMax1: "Maximum prefetch",
        galleryMax2: "Pictures (before and after)",
        galleryAutoZoom: "Zoom changes back to 100% (chrome)",
        galleryAutoZoomTip: "If you zoom in, change the zoom of the image and sidebar sections back to 100% and increase the viewable area (only valid under chrome)",
        galleryDescriptionLength1: "Maximum of annotation is",
        galleryDescriptionLength2: "Characters",
        galleryAutoOpenSites: "Regulars of urls for auto open gallery, one per line, start with @ for ViewMore",
        autoOpenViewmore: "Auto view more when open gallery",
        galleryViewmoreLayout: "Layout of ViewMore mode",
        gallerySearchData: "Site rules for search, empty it to restore",
        galleryEditSite: "Online editing site",
        imgWindow: "ImgWindow",
        imgWindowFitToScreen: "Adapt to the screen",
        imgWindowFitToScreenTip: "Adapt to be contain, not cover",
        imgWindowFitToScreenWhenSmall: "Adapt to the screen even when it's small",
        imgWindowDefaultTool: "The tool selected by default when opening the window",
        hand: "Hand",
        rotate: "Rotate",
        zoom: "Magnifier",
        imgWindowEscKey: "Esc key to close",
        imgWindowDblClickImgWindow: "Double click to close",
        imgWindowClickOutside: "Click overlayer to close by",
        imgWindowClickOutsideTip: "Only enable when Overlayer is shown",
        none: "None",
        click: "Click",
        dblclick: "Double click",
        imgWindowOverlayerShown: "Overlay",
        imgWindowOverlayerColor: "Color and Opacity",
        imgWindowShiftRotateStep1: "Rotate when hold down the Shift key on every ",
        imgWindowShiftRotateStep2: "Degree",
        imgWindowMouseWheelZoom: "MouseWheel Zoom",
        imgWindowZoomRange: "Zoom Range",
        imgWindowZoomRangeTip: "Zoom ratio (must be positive)",
        others: "Other",
        waitImgLoad: "Start to perform operations such as zooming until image is loaded",
        waitImgLoadTip: "When holding down the Ctrl key, you can temporarily execute opposite to this setting",
        debug: "Debug mode",
        customRules: "Custom rules for large image",
        firstEngine: "Preferred (first) search engine",
        refreshWhenError: "Read error, click to overload",
        switchSlide: "Switch sidebar",
        viewmore: "View more",
        countDown: "CountDown",
        customLang: "Custom language",
        defaultLang: "Auto detect",
        hideIcon: "Hide icon",
        initShow: "Invert Shortcut to show preview by default",
        stayOut: "Let float bar stay out of the image",
        galleryDownloadGap: "Download interval",
        galleryDisableArrow: "Disable arrow key"
    }
}, 
{
    name: "简体中文",
    match: ["zh-CN", "zh-SG"],
    lang: {
        saveBtn: "确定",
        saveName: "保存图片名",
        saveNameTip: "使用预设模式保存图片",
        default: "默认",
        textFirst: "优先使用图片描述",
        onlyUrl: "仅使用 URL 中的文件名",
        urlAndText: "URL + 文件描述",
        download: "下载",
        saveBtnTips: "部分选项需要刷新页面才能生效",
        additionalFeature: "额外功能，按住 alt 时生效",
        invertAdditionalFeature: "反转快捷键，默认使用额外功能",
        copy: "复制链接",
        copyImg: "复制图片",
        openInNewTab: "在新标签页打开",
        closeBtn: "取消",
        invertBtn: "反选",
        compareBtn: "对比",
        closeBtnTips: "取消本次设置，所有选项还原",
        resetLink: "恢复默认设置",
        resetLinkTips: "恢复所有设置的内容为默认值",
        share: "分享",
        suitLongImg: "长图在滚动窗口显示",
        globalkeys: "预览功能键组合: ",
        globalkeysPress: "敲击切换预览",
        globalkeysHold: "按住开启预览",
        globalkeysType: "预览触发方式：",
        closeAfterPreview: "预览结束关闭图片窗口",
        loadAll: "加载更多页",
        loadedAll: "加载完毕",
        loading: "正在加载",
        loadAllTip: "加载下一页的图片",
        viewmoreEndless: "查看更多里滚动到底自动加载下一页",
        fiddle: "弹出图片",
        fiddleTip: "弹出图片进行复杂操作",
        addImageUrls: "添加图片",
        addImageUrlsTips: "通过 url 添加更多图片",
        closeFirst: "请先关掉当前已经打开的库",
        collect: "收藏",
        collected: "已收藏",
        exitCollection: "退出收藏",
        exitCollectionTip: "点击退出收藏模式",
        noCollectionYet: "你还木有收藏任何图片",
        collectDetail: "描述",
        collectDetailTip: "给收藏的图片添加一些描述吧",
        playSlide: "播放幻灯片",
        slideGap: "间隔(s)",
        slideGapTip: "间隔时间，单位(秒)",
        slideBack: "后退",
        slideBackTip: "从后往前播放",
        slideWait: "等待图片读取",
        slideWaitTip: "从每张图片完全读取完成后才开始倒计时",
        slideSkipError: "跳过错误图片",
        slideSkipErrorTip: "快速跳过读取错误的图片",
        type: "类别",
        typeTip: "选择图片类别",
        showWithRules: "匹配到规则就显示",
        showWithRulesTip: "只要匹配到规则，不论尺寸为何都会显示图标",
        advancedRules: "高级规则",
        advancedRulesTip: "由高级规则匹配出来的",
        tpRules: "通配规则",
        tpRulesTip: "由通配规则匹配出来的",
        scaleRules: "缩放过的",
        scaleRulesTip: "js自动查找，相对页面显示的图片有缩放过的",
        noScaleRules: "无缩放过",
        noScaleRulesTip: "js自动查找，无缩放过的，但是满足一定的大小",
        smallRules: "小尺寸的",
        smallRulesTip: "小尺寸图片，实际尺寸的高和宽都小于#t#像素",
        lockSizeTip: "锁定最大尺寸",
        command: "命令",
        commandTip: "命令菜单",
        onlineEdit: "在线编辑",
        onlineEditTip: "使用#t#在线编辑该图片",
        openInNewWindow: "新窗口打开",
        openInNewWindowTip: "新窗口打开图片",
        findInPage: "定位到图片",
        findInPageTip: "滚动到当前图片所在的位置",
        viewCollection: "查看收藏",
        viewCollectionTip: "查看所有收藏的图片",
        inCollection: "收藏模式中，无法使用",
        cantFind: "图片不在文档中，或者被隐藏了，无法定位！",
        exportImages: "导出显示大图",
        exportImagesTip: "导出所有显示中的图片到新窗口",
        downloadImage: "下载当前所有",
        downloadImageTip: "下载当前库中所有显示图片",
        copyImagesUrl: "复制显示大图",
        copyImagesUrlTip: "复制所有显示中的大图地址",
        copySuccess: "已成功复制 #t# 张大图地址",
        autoRefresh: "自动重载",
        autoRefreshTip: "最后几张图片时，滚动主窗口到最底部，然后自动加载新的图片",
        enterFullsc: "进入全屏",
        exitFullsc: "退出全屏",
        config: "设置",
        openConfig: "打开设置",
        closeGallery: "关闭库",
        returnToGallery: "回到库",
        picInfo: "点击修改",
        picNote: "图片注释",
        urlFilter: "过滤链接",
        urlFilterTip: "输入关键字或正则表达式过滤链接",
        resolution: "分辨率",
        scaleRatio: "缩放比",
        similarImage: "以图搜图",
        scale: "缩放",
        horizontalFlip: "水平翻转",
        verticalFlip: "垂直翻转",
        actualBtn: "查看原始(A)",
        searchBtn: "查找原图(S)",
        galleryBtn: "查看库(G)",
        currentBtn: "查看当前(C)",
        magnifierBtn: "放大镜(M)",
        picTitle: "图片标题",
        picNum: "图片数量",
        picTips: "按住Ctrl放大",
        savePageTips: "使用“网页另存为”即可保存所有图片",
        exportImagesUrl: "导出图片链接",
        exportImagesUrlPop: "Ctrl+C复制图片链接",
        beginSearchImg: "#t#识图开始……",
        findNoPic: "未找到原图",
        findOverBeginLoad: "#t#识图结束，共找到#t#张匹配图片，开始加载第一张",
        loadNextSimilar: "原图加载失败，尝试加载下一结果……",
        loadError: "加载失败",
        openHomePage: "点击此处打开主页",
        position: "显示位置",
        positionTips: "按住ALT隐藏",
        topLeft: "图片左上角",
        topRight: "图片右上角",
        bottomRight: "图片右下角",
        bottomLeft: "图片左下角",
        topCenter: "图片正上方",
        bottomCenter: "图片正下方",
        floatBar: "浮动工具栏",
        previewFollowMouse: "使得预览图跟随鼠标指针",
        showDelay: "显示延时",
        ms: "毫秒",
        hide: "隐藏",
        hideDelay: "隐藏延时",
        forceShow: "非缩放图片，超过该尺寸，显示浮框",
        forceShowTip: "非缩放的图片大小超过下面设定的尺寸时显示浮动工具栏",
        sizeLimitOr: "以上长宽条件只需满足其一",
        px: "像素",
        minSizeLimit: "缩放图片，超过该尺寸，显示浮框",
        minSizeLimitTip: "图片被缩放(图片原始大小与实际大小不一致)后,显示长宽大于设定值时显示浮动工具栏",
        defaultSizeLimit: "图库默认筛选尺寸",
        listenBg: "监听背景图",
        backgroundColor: "背景颜色",
        listenBgTip: "在有背景图的元素上显示悬浮框",
        butonOrder: "工具栏图标排序",
        keysEnable: "启用以下快捷键",
        keysActual: "打开大图",
        keysActualTip: "当出现悬浮条时按下此按键打开大图",
        keysSearch: "查找原图",
        keysSearchTip: "当出现悬浮条时按下此按键查找原图",
        headSearchTip: "搜图",
        headSearchAll: "搜索以上全部",
        keysCurrent: "打开当前图片",
        keysCurrentTip: "当出现悬浮条时按下此按键打开当前显示的图片",
        keysMagnifier: "打开放大镜观察",
        keysMagnifierTip: "当出现悬浮条时按下此按键打开放大镜观察",
        keysGallery: "打开图库（加功能键为全局）",
        keysGalleryTip: "当出现悬浮条时按下此按键打开图库",
        openGallery: "打开图库",
        magnifier: "放大镜",
        magnifierRadius: "默认半径",
        magnifierWheelZoomEnabled: "启用滚轮缩放",
        magnifierWheelZoomRange: "滚轮缩放的倍率",
        gallery: "图库",
        galleryFitToScreen: "对图片进行缩放以适应屏幕",
        galleryFitToScreenSmall: "小图也缩放以适应屏幕",
        galleryFitToScreenTip: "适应方式为contain，非cover",
        galleryScrollEndToChange: "大图滚动到底后切换图片",
        galleryScrollEndToChangeTip: "取消上一选项后才有效",
        galleryExportType: "图片导出默认排序",
        grid: "平铺排序",
        gridBig: "原图平铺",
        list: "列表排序",
        galleryAutoLoad: "自动加载更多图片",
        galleryLoadAll: "加载更多图片时自动处理全部页",
        galleryLoadAllTip: "若页数过多可能影响体验",
        galleryDownloadWithZip: "下载所有时打包成zip",
        galleryDownloadWithZipAlert: "下载准备中，请耐心等候数十秒",
        galleryScaleSmallSize1: "实际尺寸的高和宽都小于 ",
        galleryScaleSmallSize2: " 像素则归入小尺寸图片",
        galleryShowSmallSize: "默认显示小尺寸图片",
        galleryTransition: "显示图库切换图片的特效",
        gallerySidebarPosition: "缩略图栏位置",
        bottom: "底部",
        right: "右侧",
        left: "左侧",
        top: "顶部",
        gallerySidebarSize: "高度",
        gallerySidebarSizeTip: "缩略图栏的高（如果是水平放置）或者宽（如果是垂直放置）",
        galleryMax1: "最多预读 ",
        galleryMax2: " 张图片（前后各多少张）",
        galleryAutoZoom: "缩放改回 100%（chrome）",
        galleryAutoZoomTip: "如果有放大，则把图片及 sidebar 部分的缩放改回 100%，增大可视面积（仅在 chrome 下有效）",
        galleryDescriptionLength1: "注释的最大宽度",
        galleryDescriptionLength2: " 个字符",
        galleryAutoOpenSites: "自动打开图库的网址正则，一行一条，若开头加@则自动展开图库",
        autoOpenViewmore: "打开图库时自动展开",
        galleryViewmoreLayout: "图库展开之后的布局",
        gallerySearchData: "搜图站点设置，清空还原",
        galleryEditSite: "在线编辑站点",
        imgWindow: "图片窗口",
        imgWindowFitToScreen: "适应屏幕，并且水平垂直居中",
        imgWindowFitToScreenTip: "适应方式为contain，非cover",
        imgWindowFitToScreenWhenSmall: "即使是小图片也拉伸至适应屏幕",
        imgWindowDefaultTool: "打开窗口时默认选择的工具",
        hand: "抓手",
        rotate: "旋转",
        zoom: "放大镜",
        imgWindowEscKey: "Esc键关闭",
        imgWindowDblClickImgWindow: "双击图片窗口关闭",
        imgWindowClickOutside: "点击图片外部（覆盖层）关闭",
        imgWindowClickOutsideTip: "仅当覆盖层显示时生效",
        none: "无",
        click: "单击",
        dblclick: "双击",
        imgWindowOverlayerShown: "覆盖层",
        imgWindowOverlayerColor: "颜色和不透明度",
        imgWindowShiftRotateStep1: "旋转时，按住shift键，旋转的步进",
        imgWindowShiftRotateStep2: " 度",
        imgWindowMouseWheelZoom: "滚轮缩放",
        imgWindowZoomRange: "滚轮缩放比例",
        imgWindowZoomRangeTip: "缩放比例(必须为正数)",
        others: "其它",
        waitImgLoad: "等图片完全载入后，才开始执行弹出放大等操作",
        waitImgLoadTip: "按住ctrl键的时候,可以临时执行和这个设定相反的设定",
        debug: "调试模式",
        customRules: "自定义大图规则",
        firstEngine: "首选搜图引擎",
        refreshWhenError: "读取错误，点击重载",
        switchSlide: "开关侧边栏",
        viewmore: "展开更多",
        countDown: "倒计时",
        customLang: "设定语言",
        defaultLang: "自动选择",
        hideIcon: "隐藏图标",
        initShow: "反转快捷键，默认显示预览",
        stayOut: "使浮动工具栏显示在图片外部",
        galleryDownloadGap: "下载间隔时间",
        galleryDisableArrow: "禁用方向键"
    }
},
{
    name: "正體中文",
    match: ["zh-TW", "zh-HK", "zh-MO"],
    lang: {
        saveBtn: "確定",
        saveName: "保存圖片名",
        saveNameTip: "使用預設模式保存圖片",
        default: "默認",
        textFirst: "優先使用圖片描述",
        onlyUrl: "僅使用 URL 中的文件名",
        urlAndText: "URL + 文件描述",
        download: "下載",
        saveBtnTips: "部分選項需要刷新頁面才能生效",
        additionalFeature: "額外功能，按住 alt 時生效",
        invertAdditionalFeature: "反轉快捷鍵，默認使用額外功能",
        copy: "複製鏈接",
        copyImg: "複製圖片",
        openInNewTab: "在新標籤頁打開",
        closeBtn: "取消",
        invertBtn: "反選",
        compareBtn: "對比",
        closeBtnTips: "取消本次設置，所有選項還原",
        resetLink: "恢復默認設置",
        resetLinkTips: "恢復所有設置的內容為默認值",
        share: "分享",
        suitLongImg: "長圖在滾動窗口顯示",
        globalkeys: "預覽功能鍵組合: ",
        globalkeysPress: "敲擊切換預覽",
        globalkeysHold: "按住開啟預覽",
        globalkeysType: "預覽觸發方式：",
        closeAfterPreview: "預覽結束關閉圖片窗口",
        loadAll: "載入更多",
        loadedAll: "載入完畢",
        loading: "正在載入",
        loadAllTip: "載入下一頁的圖片",
        viewmoreEndless: "查看更多裏滾動到底自動加載下一頁",
        fiddle: "彈出圖片",
        fiddleTip: "彈出圖片進行複雜操作",
        addImageUrls: "添加圖片",
        addImageUrlsTips: "通過 url 添加更多圖片",
        closeFirst: "請先關閉當前已經打開的庫",
        collect: "收藏",
        collected: "已收藏",
        exitCollection: "退出收藏",
        exitCollectionTip: "點擊退出收藏模式",
        noCollectionYet: "你還木有收藏任何圖片",
        collectDetail: "描述",
        collectDetailTip: "給收藏的圖片添加一些描述吧",
        playSlide: "播放幻燈片",
        slideGap: "間隔(s)",
        slideGapTip: "間隔時間，單位(秒)",
        slideBack: "後退",
        slideBackTip: "從後往前播放",
        slideWait: "等待圖片讀取",
        slideWaitTip: "從每張圖片完全讀取完成後才開始倒計時",
        slideSkipError: "跳過錯誤圖片",
        slideSkipErrorTip: "快速跳過讀取錯誤的圖片",
        type: "類別",
        typeTip: "選擇圖片類別",
        showWithRules: "匹配到規則就顯示",
        showWithRulesTip: "只要匹配到規則，不論尺寸為何都會顯示圖標",
        advancedRules: "高級規則",
        advancedRulesTip: "由高級規則匹配出來的",
        tpRules: "通配規則",
        tpRulesTip: "由通配規則匹配出來的",
        scaleRules: "縮放過的",
        scaleRulesTip: "js自動查找，相對頁面顯示的圖片有縮放過的",
        noScaleRules: "無縮放過",
        noScaleRulesTip: "js自動查找，無縮放過的，但是滿足一定的大小",
        smallRules: "小尺寸的",
        smallRulesTip: "小尺寸圖片，實際尺寸的高和寬都小於#t#像素",
        lockSizeTip: "鎖定最大尺寸",
        command: "命令",
        commandTip: "命令菜單",
        onlineEdit: "在線編輯",
        onlineEditTip: "使用#t#在線編輯該圖片",
        openInNewWindow: "新窗口打開",
        openInNewWindowTip: "新窗口打開圖片",
        findInPage: "定位到圖片",
        findInPageTip: "滾動到當前圖片所在的位置",
        viewCollection: "查看收藏",
        viewCollectionTip: "查看所有收藏的圖片",
        inCollection: "收藏模式中，無法使用",
        cantFind: "圖片不在文檔中，或者被隱藏了，無法定位！",
        exportImages: "導出顯示大圖",
        exportImagesTip: "導出所有顯示中的圖片到新窗口",
        downloadImage: "下載當前所有",
        downloadImageTip: "下載當前庫中所有顯示圖片",
        copyImagesUrl: "複製顯示大圖",
        copyImagesUrlTip: "複製所有顯示中的大圖地址",
        copySuccess: "已成功複製 #t# 張大圖地址",
        autoRefresh: "自動重載",
        autoRefreshTip: "最後幾張圖片時，滾動主窗口到最底部，然後自動載入新的圖片",
        enterFullsc: "進入全屏",
        exitFullsc: "退出全屏",
        config: "設置",
        openConfig: "打開設置",
        closeGallery: "關閉庫",
        returnToGallery: "回到庫",
        picInfo: "點擊修改",
        picNote: "圖片注釋",
        urlFilter: "過濾連結",
        urlFilterTip: "輸入關鍵字或正則表達式過濾連結",
        resolution: "解析度",
        scaleRatio: "縮放比",
        similarImage: "以圖搜圖",
        scale: "縮放",
        horizontalFlip: "水平翻轉",
        verticalFlip: "垂直翻轉",
        actualBtn: "查看原始(A)",
        searchBtn: "查找原圖(S)",
        galleryBtn: "查看庫(G)",
        currentBtn: "查看當前(C)",
        magnifierBtn: "放大鏡(M)",
        picTitle: "圖片標題",
        picNum: "圖片數量",
        picTips: "按住Ctrl放大",
        savePageTips: "使用「網頁另存為」即可保存所有圖片",
        exportImagesUrl: "導出圖片鏈接",
        exportImagesUrlPop: "Ctrl+C複製圖片鏈接",
        beginSearchImg: "#t#識圖開始……",
        findNoPic: "未找到原圖",
        findOverBeginLoad: "#t#識圖結束，共找到#t#張匹配圖片，開始載入第一張",
        loadNextSimilar: "原圖載入失敗，嘗試載入下一結果……",
        loadError: "載入失敗",
        openHomePage: "點擊此處打開主頁",
        position: "顯示位置",
        positionTips: "按住ALT隱藏",
        topLeft: "圖片左上角",
        topRight: "圖片右上角",
        bottomRight: "圖片右下角",
        bottomLeft: "圖片左下角",
        topCenter: "圖片正上方",
        bottomCenter: "圖片正下方",
        floatBar: "浮動工具欄",
        previewFollowMouse: "使得預覽圖跟隨鼠標指針",
        showDelay: "顯示延時",
        ms: "毫秒",
        hide: "隱藏",
        hideDelay: "隱藏延時",
        forceShow: "非縮放圖片，超過該尺寸，顯示浮框",
        forceShowTip: "非縮放的圖片大小超過下面設定的尺寸時顯示浮動工具欄",
        sizeLimitOr: "以上長寬條件只需滿足其一",
        px: "像素",
        minSizeLimit: "縮放圖片，超過該尺寸，顯示浮框",
        minSizeLimitTip: "圖片被縮放(圖片原始大小與實際大小不一致)後,顯示長寬大於設定值時顯示浮動工具欄",
        defaultSizeLimit: "圖庫默認篩選尺寸",
        listenBg: "監聽背景圖",
        backgroundColor: "背景顔色",
        listenBgTip: "在有背景圖的元素上顯示懸浮框",
        butonOrder: "工具欄圖標排序",
        keysEnable: "啟用以下快捷鍵",
        keysActual: "打開大圖",
        keysActualTip: "當出現懸浮條時按下此按鍵打開大圖",
        keysSearch: "查找原圖",
        keysSearchTip: "當出現懸浮條時按下此按鍵查找原圖",
        headSearchTip: "搜圖",
        headSearchAll: "搜索以上全部",
        keysCurrent: "打開當前圖片",
        keysCurrentTip: "當出現懸浮條時按下此按鍵打開當前顯示的圖片",
        keysMagnifier: "打開放大鏡觀察",
        keysMagnifierTip: "當出現懸浮條時按下此按鍵打開放大鏡觀察",
        keysGallery: "打開圖庫（加功能鍵為全局）",
        keysGalleryTip: "當出現懸浮條時按下此按鍵打開圖庫",
        openGallery: "打開圖庫",
        magnifier: "放大鏡",
        magnifierRadius: "默認半徑",
        magnifierWheelZoomEnabled: "啟用滾輪縮放",
        magnifierWheelZoomRange: "滾輪縮放的倍率",
        gallery: "圖庫",
        galleryFitToScreen: "對圖片進行縮放以適應屏幕",
        galleryFitToScreenSmall: "小圖也縮放以適應屏幕",
        galleryFitToScreenTip: "適應方式為contain，非cover",
        galleryScrollEndToChange: "大圖滾動到底後切換圖片",
        galleryScrollEndToChangeTip: "取消上一選項後才有效",
        galleryExportType: "圖片導出默認排序",
        grid: "平鋪排序",
        gridBig: "原圖平鋪",
        list: "列表排序",
        galleryAutoLoad: "自動載入更多圖片",
        galleryLoadAll: "載入更多圖片時自動處理全部頁",
        galleryLoadAllTip: "若頁數過多可能影響體驗",
        galleryDownloadWithZip: "下載所有時打包成zip",
        galleryDownloadWithZipAlert: "正在打包，請耐心等候數十秒",
        galleryScaleSmallSize1: "實際尺寸的高和寬都小於 ",
        galleryScaleSmallSize2: " 像素則歸入小尺寸圖片",
        galleryShowSmallSize: "默認顯示小尺寸圖片",
        galleryTransition: "顯示圖庫切換圖片的特效",
        gallerySidebarPosition: "縮略圖欄位置",
        bottom: "底部",
        right: "右側",
        left: "左側",
        top: "頂部",
        gallerySidebarSize: "高度",
        gallerySidebarSizeTip: "縮略圖欄的高（如果是水平放置）或者寬（如果是垂直放置）",
        galleryMax1: "最多預讀 ",
        galleryMax2: " 張圖片（前後各多少張）",
        galleryAutoZoom: "縮放改回 100%（chrome）",
        galleryAutoZoomTip: "如果有放大，則把圖片及 sidebar 部分的縮放改回 100%，增大可視面積（僅在 chrome 下有效）",
        galleryDescriptionLength1: "注釋的最大寬度",
        galleryDescriptionLength2: " 個字元",
        galleryAutoOpenSites: "自動打開圖庫的網址正則，一行一條，若前綴@則自動展開圖庫",
        autoOpenViewmore: "打開圖庫時自動展開",
        galleryViewmoreLayout: "圖庫展開之後的佈局",
        gallerySearchData: "搜圖站點設置，清空還原",
        galleryEditSite: "在線編輯站點",
        imgWindow: "圖片窗口",
        imgWindowFitToScreen: "適應屏幕，並且水平垂直居中",
        imgWindowFitToScreenTip: "適應方式為contain，非cover",
        imgWindowFitToScreenWhenSmall: "即使是小圖片也拉伸至適應屏幕",
        imgWindowDefaultTool: "打開窗口時默認選擇的工具",
        hand: "抓手",
        rotate: "旋轉",
        zoom: "放大鏡",
        imgWindowEscKey: "Esc鍵關閉",
        imgWindowDblClickImgWindow: "雙擊圖片窗口關閉",
        imgWindowClickOutside: "點擊圖片外部關閉（覆蓋層）",
        imgWindowClickOutsideTip: "僅當覆蓋層顯示時生效",
        none: "無",
        click: "單擊",
        dblclick: "雙擊",
        imgWindowOverlayerShown: "覆蓋層",
        imgWindowOverlayerColor: "顏色和不透明度",
        imgWindowShiftRotateStep1: "旋轉時，按住shift鍵，旋轉的步進",
        imgWindowShiftRotateStep2: " 度",
        imgWindowMouseWheelZoom: "滾輪縮放",
        imgWindowZoomRange: "滾輪縮放比例",
        imgWindowZoomRangeTip: "縮放比例(必須為正數)",
        others: "其它",
        waitImgLoad: "等圖片完全載入後，才開始執行彈出放大等操作",
        waitImgLoadTip: "按住ctrl鍵的時候,可以臨時執行和這個設定相反的設定",
        debug: "調試模式",
        customRules: "自定義大圖規則",
        firstEngine: "首選搜圖引擎",
        refreshWhenError: "讀取錯誤，點擊重載",
        switchSlide: "開關側邊欄",
        viewmore: "展開更多",
        countDown: "倒計時",
        customLang: "設定語言",
        defaultLang: "自動選擇",
        hideIcon: "隱藏圖標",
        initShow: "反轉快捷鍵，默認顯示預覽",
        stayOut: "使浮動工具欄顯示在圖片外部",
        galleryDownloadGap: "下載間隔時間",
        galleryDisableArrow: "禁用方向鍵"
    }
},
{
    name: "Português",
    match: ["pt", "pt-BR"],
    lang: {
        //Português por AstroCoelestis.
        saveBtn: "Salvar",
        saveName: "Nome ao salvar",
        saveNameTip: "Como será definido o nome do arquivo da imagem ao salva-la",
        default: "Padrão",
        textFirst: "Informações primeiro se existirem",
        onlyUrl: "Apenas o URL",
        urlAndText: "URL + Informações",
        download: "Baixar",
        saveBtnTips: "Talvez você precise atualizar a página para que alguma opções entrem em vigor",
        additionalFeature: "Recursos adicionais, entram em vigor quando alt é pressionado",
        invertAdditionalFeature: "Inverter teclas de atalho, usar recursos adicionais por padrão",
        copy: "Copiar link",
        copyImg: "Copiar dados da imagem",
        openInNewTab: "Abrir em nova aba",
        closeBtn: "Cancelar",
        invertBtn: "Inverter",
        compareBtn: "Comparar",
        closeBtnTips: "Descarta as alterações e restaura as configurações anteriores",
        resetLink: "Restaurar definições originais",
        resetLinkTips: "Descarta as alterações e restaura todas as configurações originais",
        share: "Compartilhar",
        suitLongImg: "Adaptar imagens longas na janela de rolagem",
        globalkeys: "Atalho para ativar a Pré-visualização",
        globalkeysPress: "Pressionar para ativar",
        globalkeysHold: "Segurar para ativar",
        globalkeysType: "Método de ativação da Pré-visualização",
        closeAfterPreview: "Fechar a janela da imagem após a Pré-visualização",
        loadAll: "Carregar mais páginas",
        loadedAll: "Carregamento concluído",
        loading: "Carregando... ",
        loadAllTip: "Carrega mais páginas para adicionar mais imagens à galeria",
        viewmoreEndless: "Rolar até o final no modo Ver Mais carrega automaticamente a próxima página",
        fiddle: "Operações",
        fiddleTip: "Abre a imagem atual em uma janela flutuante para realizar operações complexas",
        addImageUrls: "Adicionar imagens",
        addImageUrlsTips: "Adicione mais imagens à galeria usando links",
        closeFirst: "Fechar a Galeria existente primeiro",
        collect: "Coleção",
        collected: "Adicionada à Coleção",
        exitCollection: "Sair da Coleção",
        exitCollectionTip: "Clique para sair do modo de Coleção",
        noCollectionYet: "Não há imagens na coleção",
        collectDetail: "Descrição",
        collectDetailTip: "Adicione uma descrição à sua coleção de imagens favoritas",
        playSlide: "Apresentação de Slides",
        slideGap: "Intervalo",
        slideGapTip: "Intervalo de tempo, em segundos",
        slideBack: "De trás para frente",
        slideBackTip: "Reproduz a apresentação de Slides de trás para frente",
        slideWait: "Aguardar a leitura da imagem",
        slideWaitTip: "A contagem regressiva só começa depois que a imagem é totalmente carregada",
        slideSkipError: "Ignorar imagens com erro",
        slideSkipErrorTip: "Ignora as imagens que não podem ser carregadas",
        type: "Categorias",
        typeTip: "Organiza as imagens por regras. Ao desmarcar uma regra, as imagens correspondentes ficarão ocultas",
        showWithRules: "Forçar a exibição da Barra de Ferramentas",
        showWithRulesTip: "Mostra a Barra de Ferramentas se a imagem corresponder às regras, não importa o tamanho",
        advancedRules: "Regras Avançadas",
        advancedRulesTip: "Imagens compatíveis com as regras avançadas",
        tpRules: "Regras Curinga",
        tpRulesTip: "Imagens compatíveis com as regras curinga",
        scaleRules: "Imagens ampliadas",
        scaleRulesTip: "Imagens automaticamente carregadas e ampliadas",
        noScaleRules: "Imagens não ampliadas",
        noScaleRulesTip: "Imagens automaticamente carregadas, mas não ampliadas",
        smallRules: "Imagens pequenas",
        smallRulesTip: "Imagens pequenas cujo tamanho real da altura e largura são menores que #t# píxeis",
        lockSizeTip: "Bloquear tamanho máximo",
        command: "Ações",
        commandTip: "Menu de Ações da Galeria",
        onlineEdit: "Editar a imagem atual",
        onlineEditTip: "Edite a imagem atual usando o serviço online #t#",
        openInNewWindow: "Abrir em nova janela",
        openInNewWindowTip: "Abre a imagem atual em uma nova guia",
        findInPage: "Localizar a imagem na página",
        findInPageTip: "Role a página até onde está a imagem atual",
        viewCollection: "Ver a coleção",
        viewCollectionTip: "Veja todas as imagens adicionadas à sua coleção",
        inCollection: "Impossível usar na Coleção",
        cantFind: "A imagem não está no documento ou está oculta e não pode ser localizada!",
        exportImages: "Exportar todas as imagens",
        exportImagesTip: "Abre todas as imagens grandes da galeria em uma nova guia",
        downloadImage: "Baixar todas as imagens",
        downloadImageTip: "Baixa todas as imagens da galeria (DICA: Use a opção de compactação ZIP)",
        copyImagesUrl: "Copiar os links das imagens",
        copyImagesUrlTip: "Copia os links das imagens da Galeria para a sua área de transferência",
        copySuccess: "#t# links copiados com sucesso!",
        autoRefresh: "Auto carregar a página",
        autoRefreshTip: "Quando as últimas imagens forem visualizadas, a página descerá automaticamente para carregar mais imagens",
        enterFullsc: "Entrar em tela cheia",
        exitFullsc: "Sair da tela cheia",
        config: "Configurações",
        openConfig: "Configurações",
        closeGallery: "Sair da Galeria",
        returnToGallery: "Voltar para a Galeria",
        picInfo: "Clique para alterar",
        picNote: "Anotação da imagem",
        urlFilter: "Filtrar os links",
        urlFilterTip: "Filtre os links usando palavras-chave ou expressões regulares",
        resolution: "Resolução da imagem",
        scaleRatio: "Relação de escala da imagem",
        similarImage: "Pesquisa por Imagem",
        scale: "Ampliar",
        horizontalFlip: "Inverter horizontalmente",
        verticalFlip: "Inverter verticalmente",
        actualBtn: "Ver a imagem original (A)",
        searchBtn: "Pesquisar a imagem original (S)",
        galleryBtn: "Abrir a imagem na galeria (G)",
        currentBtn: "Ver a imagem atual (C)",
        magnifierBtn: "Ampliar usando a Lupa (M)",
        picTitle: "Título da imagem",
        picNum: "Quantidade de imagens",
        picTips: "Segure CTRL e passe o mouse sobre uma imagem para vê-la ampliada",
        savePageTips: "CTRL+S para salvar essa página e baixar todas as imagens",
        exportImagesUrl: "Exportar URL da imagem",
        exportImagesUrlPop: "Use Ctrl+C para copiar os links das imagens",
        beginSearchImg: "#t# iniciando a Pesquisa por Imagem... ",
        findNoPic: "A imagem original não foi encontrada",
        findOverBeginLoad: "#t# fim da pesquisa. Foram encontradas #t# imagens correspondentes, carregando a primeira... ",
        loadNextSimilar: "A imagem original falhou ao carregar, tentando carregar o próximo resultado... ",
        loadError: "Falha ao carregar",
        openHomePage: "Abrir página inicial",
        position: "Posição da Barra de Ferramentas",
        positionTips: "Segure ALT para ocultar a Barra de Ferramentas",
        topLeft: "Canto superior esquerdo",
        topRight: "Canto superior direito",
        bottomRight: "Canto inferior direito",
        bottomLeft: "Canto inferior esquerdo",
        topCenter: "Ao lado da imagem",
        bottomCenter: "Abaixo da imagem",
        floatBar: "Barra de Ferramentas",
        previewFollowMouse: "Mostrar a pré-visualização ao lado do mouse",
        showDelay: "Atraso para exibir a Barra de Ferramentas",
        ms: "ms",
        hide: "Ocultar a Barra de Ferramentas",
        hideDelay: "Atraso para ocultar a Barra de Ferramentas",
        forceShow: "Exibir a Barra de Ferramentas sobre imagens não ampliadas",
        forceShowTip: "Exibe a Barra de Ferramentas quando o tamanho da imagem não ampliada excede o tamanho definido ao lado",
        sizeLimitOr: "Exibir se corresponder por altura OU largura",
        px: "px",
        minSizeLimit: "Exibir a Barra de Ferramentas sobre imagens ampliadas",
        minSizeLimitTip: "Exibe a Barra de Ferramentas quando o tamanho da imagem ampliada (tamanho original é diferente do tamanho real) exceder o tamanho definido ao lado",
        defaultSizeLimit: "Limite de tamanho padrão para imagens da Galeria",
        listenBg: "Monitorar imagens em segundo plano",
        backgroundColor: "Cor do plano de fundo",
        listenBgTip: "Exibe a Barra de Ferramentas em uma imagem no plano de fundo",
        butonOrder: "Ordem das ferramentas",
        keysEnable: "Atalhos para ativar a ferramentas",
        keysActual: "Abrir a imagem original",
        keysActualTip: "Pressione esta tecla para abrir a imagem original quando a Barra de Ferramentas aparecer",
        keysSearch: "Encontre a imagem original",
        keysSearchTip: "Pressione esta tecla para pesquisar a imagem original quando a Barra de Ferramentas aparecer",
        headSearchTip: "Use um desses sites para pesquisar por imagens semelhantes",
        headSearchAll: "Pesquisar em todos os sites",
        keysCurrent: "Abrir a imagem atual",
        keysCurrentTip: "Pressione esta tecla para abrir a imagem atual quando a Barra de Ferramentas aparecer",
        keysMagnifier: "Usar a ferramenta Lupa",
        keysMagnifierTip: "Pressione esta tecla para usar a Lupa quando a Barra de Ferramentas aparecer",
        keysGallery: "Abrir a imagem na Galeria",
        keysGalleryTip: "Pressione esta tecla para abrir a imagem na Galeria quando a Barra de Ferramentas aparecer",
        openGallery: "Abrir a Galeria",
        magnifier: "Lupa",
        magnifierRadius: "Tamanho padrão da lupa",
        magnifierWheelZoomEnabled: "Permitir ampliação com a roda do mouse",
        magnifierWheelZoomRange: "Faixa de ampliação da lupa",
        gallery: "Galeria",
        galleryFitToScreen: "Ampliar a imagem para caber na tela",
        galleryFitToScreenSmall: "Ampliar imagens pequenas também",
        galleryFitToScreenTip: "Amplia a imagem para caber, não cobrir",
        galleryScrollEndToChange: "Mudar de imagem ao rolar até o final",
        galleryScrollEndToChangeTip: "Muda automaticamente para a próxima imagem ao rolar uma imagem longa. Válido após cancelar a opção anterior",
        galleryExportType: "Classificação padrão das imagens exportadas",
        grid: "Classificação em blocos",
        gridBig: "Classificação original",
        list: "Classificação em lista",
        galleryAutoLoad: "Carregar automaticamente mais imagens na página",
        galleryLoadAll: "Processar automaticamente a página ao carregar mais imagens",
        galleryLoadAllTip: "Processar muito uma página pode afetar a sua experiência",
        galleryDownloadWithZip: "Comprimir para um arquivo ZIP quando baixar",
        galleryDownloadWithZipAlert: "Comprimindo, espere um pouco por favor",
        galleryScaleSmallSize1: "Se a altura e a largura reais forem menor que ",
        galleryScaleSmallSize2: " píxeis, a imagem será classificada como pequena",
        galleryShowSmallSize: "Exibir imagens pequenas por padrão",
        galleryTransition: "Exibir efeitos de transição de imagens na galeria",
        gallerySidebarPosition: "Posição da barra de miniaturas",
        bottom: "Inferior",
        right: "Direita",
        left: "Esquerda",
        top: "Superior",
        gallerySidebarSize: "Tamanho",
        gallerySidebarSizeTip: "A altura (se for horizontal) ou a largura (se for vertical) da barra de miniaturas",
        galleryMax1: "Cache máximo de ",
        galleryMax2: " imagens (antes e depois)",
        galleryAutoZoom: "A ampliação volta para 100% (Chrome)",
        galleryAutoZoomTip: "Ao ampliar, altera o zoom da imagem e da barra de miniaturas de volta para 100%, aumentando a área visível (válido apenas no Chrome)",
        galleryDescriptionLength1: "Largura máxima do comentário é de ",
        galleryDescriptionLength2: " caracteres",
        galleryAutoOpenSites: "Regras de links para abrir a Galeria automaticamente. Comece com @ para o modo Ver Mais. Escreva uma regra por linha",
        autoOpenViewmore: "Expandir o modo Ver Mais ao abrir a Galeria",
        galleryViewmoreLayout: "Aparência do modo Ver Mais",
        gallerySearchData: "Regras de sites para pesquisa por imagem. Esvazie para restaurar",
        galleryEditSite: "Site de edição online",
        imgWindow: "Imagem",
        imgWindowFitToScreen: "Adaptar a imagem à tela",
        imgWindowFitToScreenTip: "Adapta a imagem à tela sem permitir que ela fique fora da visão",
        imgWindowFitToScreenWhenSmall: "Adaptar a imagem à tela, mesmo se for pequena",
        imgWindowDefaultTool: "Ferramenta padrão ao exibir a imagem flutuante",
        hand: "Mover",
        rotate: "Girar",
        zoom: "Lupa",
        imgWindowEscKey: "Fechar com a tecla Esc",
        imgWindowDblClickImgWindow: "Fechar com clique duplo",
        imgWindowClickOutside: "Fechar ao clicar na sobreposição",
        imgWindowClickOutsideTip: "Só tem efeito quando a opção SOBREPOSIÇÃO está marcada",
        none: "Nenhum",
        click: "Clique único",
        dblclick: "Clique duplo",
        imgWindowOverlayerShown: "Sobreposição",
        imgWindowOverlayerColor: "Cor e Opacidade",
        imgWindowShiftRotateStep1: "Segure Shift para girar a cada ",
        imgWindowShiftRotateStep2: " grau(s)",
        imgWindowMouseWheelZoom: "Permitir a ampliação com a roda do mouse",
        imgWindowZoomRange: "Faixa de ampliação",
        imgWindowZoomRangeTip: "Valores usados ao ampliar a imagem (precisam ser positivos)",
        others: "Outros",
        waitImgLoad: "Aguardar o carregarregamento da imagem antes de realizar operações como Ampliar",
        waitImgLoadTip: "Pressionando Ctrl você pode temporariamente ignorar esta configuração",
        debug: "Modo de depuração",
        customRules: "Regras personalizadas para imagens grandes",
        firstEngine: "Motor de busca preferencial (primeiro)",
        refreshWhenError: "Erro de leitura, clique para recarregar",
        switchSlide: "Alternar a barra lateral",
        viewmore: "Ver Mais",
        countDown: "Contagem regressiva",
        customLang: "Definir o idioma",
        defaultLang: "Auto",
        hideIcon: "Ocultar a Barra de Ferramentas",
        initShow: "Inverter atalho para exibir a Pré-visualização por padrão",
        stayOut: "Permitir que a Barra de Ferramentas fique fora da imagem",
        galleryDownloadGap: "Intervalo para baixar",
        galleryDisableArrow: "Desativar as teclas de seta"
    }
},
{
    name: "Русский",
    match: ["ru", "ru-RU"],
    lang: {
        //Русский перевод by RX-3200 и vanja-san.
        saveBtn: "Сохранить",
        saveName: "Сохранять название",
        saveNameTip: "Используйте для сохранения изображений с оригинальным названием",
        default: "По умолчанию",
        textFirst: "Описание изображения",
        onlyUrl: "Только имя файла у ссылки",
        urlAndText: "Ссылка + описание файла",
        download: "Скачать",
        saveBtnTips: "Чтобы некоторые параметры вступили в силу, необходимо обновить страницу.",
        additionalFeature: "Дополнительные функции, вступают в силу при нажатии клавиши Alt",
        invertAdditionalFeature: "Инвертировать сочетания клавиш, использовать дополнительные функции по умолчанию",
        copy: "Копировать ссылку",
        copyImg: "Копировать данные изображения",
        openInNewTab: "Открыть в новой вкладке",
        closeBtn: "Закрыть",
        invertBtn: "Откатить",
        compareBtn: "Сравнивать",
        closeBtnTips: "Отменяет эту настройку и восстанавливает все параметры",
        resetLink: "Восстановить по умолчанию",
        resetLinkTips: "Восстанавливает содержимое всех параметров к значениям по умолчанию",
        share: "Поделиться",
        suitLongImg: "Отображать прокрутку для слишком длинных изображений",
        globalkeys: "Комбинация клавиш предпросмотра: ",
        globalkeysPress: "Нажмите, чтобы открыть предварительный просмотр",
        globalkeysHold: "Нажмите и удерживайте, чтобы открыть предварительный просмотр",
        globalkeysType: "Метод запуска предпросмотра: ",
        closeAfterPreview: "Закрывать окно изображения, когда предпросмотр завершается",
        loadAll: "Загружать больше страниц",
        loadedAll: "Загрузка завершена",
        loading: "Загрузка",
        loadAllTip: "Загружать изображения со следующей страницы",
        viewmoreEndless: "Прокрутите страницу до конца, чтобы автоматически загружать следующую страницу",
        fiddle: "Всплывающее изображение",
        fiddleTip: "Всплывающие изображения для сложных операций",
        addImageUrls: "Добавить изображение",
        addImageUrlsTips: "Добавляйте больше изображений по ссылке",
        closeFirst: "Сначала закройте все галереи, которые сейчас открыты.",
        collect: "Добавить в коллекцию",
        collected: "В коллекции",
        exitCollection: "Закрыть коллекцию",
        exitCollectionTip: "Нажмите, чтобы выйти из режима коллекционирования",
        noCollectionYet: "В вашей коллекции нет ни одного изображения",
        collectDetail: "Описание",
        collectDetailTip: "Добавьте описание к изображениям в коллекции",
        playSlide: "Воспроизвести слайд-шоу",
        slideGap: "Интервал(ов)",
        slideGapTip: "Время интервала, в секундах",
        slideBack: "От конца",
        slideBackTip: "Воспроизведение от конца к началу",
        slideWait: "Ожидание считывания изображения",
        slideWaitTip: "Обратный отсчёт начинаётся только после того, как все изображения будут полностью считаны",
        slideSkipError: "Пропускать изображения с ошибкой",
        slideSkipErrorTip: "Быстро пропускать изображения, которые считываются с ошибкой",
        type: "Тип",
        typeTip: "Выберите тип изображений",
        showWithRules: "Отображается при соответствии правила",
        showWithRulesTip: "Если правило соблюдено, иконка будет отображаться независимо от размера",
        advancedRules: "Расширенные правила",
        advancedRulesTip: "Соответствует расширенным правилам",
        tpRules: "Правила подстановочных знаков",
        tpRulesTip: "Соответствует правилу подстановочных знаков",
        scaleRules: "Масштабированные",
        scaleRulesTip: "JS автоматически обнаружает, что изображения отображаемые на странице, были масштабированы",
        noScaleRules: "Без масштабирования",
        noScaleRulesTip: "JS автоматически обнаружает, что изображения отображаемые на странице, не были масштабированы",
        smallRules: "Небольшой размер",
        smallRulesTip: "Изображения небольшого размера, высота и ширина фактического размера меньше, чем #t# пикселей",
        lockSizeTip: "Зафиксировать максимальный размер",
        command: "Команда",
        commandTip: "Меню команд",
        onlineEdit: "Онлайн-редактирование",
        onlineEditTip: "Отредактируйте это изображение онлайн с помощью #t#",
        openInNewWindow: "Открыть в новом окне",
        openInNewWindowTip: "Открывает изображение в новом окне",
        findInPage: "Перейти к изображению",
        findInPageTip: "Прокручивает туда, где находится текущее изображение",
        viewCollection: "Открыть коллекцию",
        viewCollectionTip: "Посмотрите все изображения в коллекции",
        inCollection: "Недоступно в режиме коллекционирования",
        cantFind: "Изображение отсутствует в документе или скрыто и не может быть найдено!",
        exportImages: "Экспортировать показанные увеличенные изображения",
        exportImagesTip: "Экспортируйте все отображаемые изображения в новое окно",
        downloadImage: "Скачать все текущие",
        downloadImageTip: "Скачайте все отображаемые изображения в текущей галерее",
        copyImagesUrl: "Копировать показаные увеличенные изображения",
        copyImagesUrlTip: "Скопируйте ссылки всех показанных изображений большего размера",
        copySuccess: "Ссылка увеличенного изображения #t# успешно скопирована",
        autoRefresh: "Автоперезагрузка",
        autoRefreshTip: "Когда дойдёте до последних изображений, прокрутите главное окно вниз для автоматической загрузки новых изображений.",
        enterFullsc: "Полноэкранный режим",
        exitFullsc: "Выйти из полноэкранного режима",
        config: "Параметры",
        openConfig: "Открывает параметры",
        closeGallery: "Закрыть галерею",
        returnToGallery: "Вернуться в галерею",
        picInfo: "Нажмите, чтобы изменить",
        picNote: "Заметка к изображению",
        urlFilter: "Фильтровать ссылки",
        urlFilterTip: "Введите ключевые слова или регулярные выражения для фильтрации ссылок",
        resolution: "Разрешение",
        scaleRatio: "Коэффициент масштабирования",
        similarImage: "Поиск по изображению",
        scale: "Масштаб",
        horizontalFlip: "Отразить по горизонтали",
        verticalFlip: "Отразить по вертикали",
        actualBtn: "Открыть оригинал (А)",
        searchBtn: "Найти оригинальное изображение (S)",
        galleryBtn: "Открыть галерею (G)",
        currentBtn: "Открыть текущее (C)",
        magnifierBtn: "Открыть лупу (M)",
        picTitle: "Подпись к изображению",
        picNum: "Количество изображений",
        picTips: "Удерживайте Ctrl, чтобы увеличить масштаб",
        savePageTips: "Используйте «Сохранить страницу как», чтобы сохранить все изображения",
        exportImagesUrl: "Экспорт ссылки изображение",
        exportImagesUrlPop: "Нажмите Ctrl+C, чтобы скопировать ссылку на изображение",
        beginSearchImg: "Распознавание изображения #t#...",
        findNoPic: "Оригинальное изображение не найдено",
        findOverBeginLoad: "Завершено распознавания #t#, всего найдено #t# подходящих изображений, начинаем загрузку первого",
        loadNextSimilar: "Не удалось загрузить оригинальное изображение, попробуйте загрузить следующий результат...",
        loadError: "Ошибка загрузки",
        openHomePage: "Нажмите здесь, чтобы открыть домашнюю страницу",
        position: "Показать расположение",
        positionTips: "Чтобы скрыть, нажмите удерживая Alt",
        topLeft: "Верхний левый угол изображения",
        topRight: "Верхний правый угол изображения",
        bottomRight: "Нижний правый угол изображения",
        bottomLeft: "Нижний левый угол изображения",
        topCenter: "Над изображением",
        bottomCenter: "Под изображением",
        floatBar: "Плавающая панель",
        previewFollowMouse: "Заставить предварительный просмотр следовать за указателем мыши",
        showDelay: "Задержка до отображения",
        ms: "мс.",
        hide: "Скрыть",
        hideDelay: "Задержка до скрытия",
        forceShow: "Изображения без масштабирования, превышающие этот размер, отображают плавающую панель",
        forceShowTip: "Отображать плавающую панель, когда размер немасштабированного изображения превышает размер, установленный ниже",
        sizeLimitOr: "Должно быть соблюдено только одно из вышеуказанных условий длины и ширины",
        px: "пикс.",
        minSizeLimit: "Масштабировать изображения сверх этого размера для отображения плавающей панели",
        minSizeLimitTip: "При масштабировании изображения (оригинальный размер которого не совпадает с фактическим), когда длина и ширина больше установленного значения, отображается плавающая панель.",
        defaultSizeLimit: "Фильтр размера галереи по умолчанию",
        listenBg: "Прослушивать фоновые изображения",
        backgroundColor: "Цвет фона",
        listenBgTip: "Отображает плавающую панель на элементе с фоновым изображением",
        butonOrder: "Сортировка иконок плавающей панели",
        keysEnable: "Включить следующие сочетания клавиш",
        keysActual: "Открыть увеличенное изображение",
        keysActualTip: "Когда появится плавающая панель, нажмите эту кнопку, чтобы открыть увеличенное изображение",
        keysSearch: "Найти оригинальное изображение",
        keysSearchTip: "Когда появится плавающая панель, нажмите эту кнопку, чтобы найти оригинальное изображение",
        headSearchTip: "Поиск изображений",
        headSearchAll: "Выполняйте поиск по всему вышеперечисленному",
        keysCurrent: "Открыть текущее изображение",
        keysCurrentTip: "Когда появится плавающая  панель, нажмите эту кнопку, чтобы открыть отображаемое в данный момент изображение",
        keysMagnifier: "Открыть лупу",
        keysMagnifierTip: "Когда появится плавающая панель, нажмите эту кнопку, чтобы открыть лупу и рассмотреть изображение",
        keysGallery: "Открыть галерею (плюс функциональные клавиши для глобального)",
        keysGalleryTip: "Когда появится плавающая панель, нажмите эту кнопку, чтобы открыть галерею",
        openGallery: "Открыть галерею",
        magnifier: "Лупа",
        magnifierRadius: "Радиус по умолчанию",
        magnifierWheelZoomEnabled: "Включить масштабирование прокруткой колёсиком мыши",
        magnifierWheelZoomRange: "Множитель масштабирования прокруткой колёсиком мышки",
        gallery: "Галерея",
        galleryFitToScreen: "Масштабировать изображения под размер экрана",
        galleryFitToScreenSmall: "Маленькие изображения также масштабируется в соответствии с размером экрана",
        galleryFitToScreenTip: "Метод адаптации - содержать, а не покрывать",
        galleryScrollEndToChange: "Переключать изображение после прокрутки до конца вниз",
        galleryScrollEndToChangeTip: "Работает только после отмены предыдущего параметра",
        galleryExportType: "Экспорт сортировки изображений по умолчанию",
        grid: "Сетка",
        gridBig: "Оригинальное изображение в сетке",
        list: "Список",
        galleryAutoLoad: "Автозагружать больше изображений",
        galleryLoadAll: "Автоматически обрабатывать все страницы при загрузке большего количества изображений",
        galleryLoadAllTip: "Если страниц слишком много, это может повлиять на скорость работы",
        galleryDownloadWithZip: "Скачивать все в zip-архиве",
        galleryDownloadWithZipAlert: "Подготовка скачивания, подождите несколько секунд",
        galleryScaleSmallSize1: "Если высота и ширина фактического размера меньше ",
        galleryScaleSmallSize2: " пикс., то оно классифицируется как изображение маленького размера",
        galleryShowSmallSize: "По умолчанию отображать изображения маленького размера",
        galleryTransition: "Отображать эффекты переключения изображений в галерее",
        gallerySidebarPosition: "Расположение панели иконок",
        bottom: "Снизу",
        right: "Справа",
        left: "Слева",
        top: "Сверху",
        gallerySidebarSize: "Высота",
        gallerySidebarSizeTip: "Высота (при горизонтальном расположении) или ширина (при вертикальном расположении) панели иконок",
        galleryMax1: "Максимальное количество изображений для ",
        galleryMax2: " предпросмотра (сколько до и после)",
        galleryAutoZoom: "Вернуть масштаб на 100% (chrome)",
        galleryAutoZoomTip: "Если есть увеличение, измените масштаб изображения и боковой панели обратно на 100%, чтобы увеличить визуальную область (допустимо только в Chrome)",
        galleryDescriptionLength1: "Макс. ширина комментария составляет",
        galleryDescriptionLength2: " символа",
        galleryAutoOpenSites: "Автооткрывать ссылки правила галереи, по одной строке за раз, и авторасширять галерею, если оно начинается с @",
        autoOpenViewmore: "Авторасширять при открытии галереи",
        galleryViewmoreLayout: "Макет после расширения галереи",
        gallerySearchData: "Поиск настроек сайта, очистка и восстановление",
        galleryEditSite: "Сайт онлайн-редактирования",
        imgWindow: "Окно изображения",
        imgWindowFitToScreen: "Адаптируется под размер экрана и выравнивается",
        imgWindowFitToScreenTip: "Метод адаптации - contain, а не cover",
        imgWindowFitToScreenWhenSmall: "Даже маленькие изображения растягиваются по размеру экрана",
        imgWindowDefaultTool: "Инструмент, выбранный по умолчанию при открытии окна",
        hand: "Захват",
        rotate: "Вращение",
        zoom: "Масштаб",
        imgWindowEscKey: "Нажмите Esc для закрытия",
        imgWindowDblClickImgWindow: "Дважды щёлкните по окну с изображением для закрытия",
        imgWindowClickOutside: "Щёлкните за пределами изображения (оверлеем) для закрытия",
        imgWindowClickOutsideTip: "Действует только при отображении оверлея",
        none: "Ничего",
        click: "Щелчок",
        dblclick: "Двойной щелчок",
        imgWindowOverlayerShown: "Оверлей",
        imgWindowOverlayerColor: "Цвет и непрозрачность",
        imgWindowShiftRotateStep1: "При вращении удерживайте Shift и вращайте с шагом в",
        imgWindowShiftRotateStep2: " градусов",
        imgWindowMouseWheelZoom: "Масштабирование колесом прокрутки",
        imgWindowZoomRange: "Масштабирование колесом прокрутки",
        imgWindowZoomRangeTip: "Масштабирование (должно быть положительным числом)",
        others: "Другое",
        waitImgLoad: "Подождите, пока изображение полностью загрузится, прежде чем выполнять такие операции, как масштабирование во всплывающем окне.",
        waitImgLoadTip: "Удерживая Ctrl, можно временно выполнить настройку, противоположную этой",
        debug: "Отладка",
        customRules: "Пользовательские правила для больших изображений",
        firstEngine: "Предпочитаемая поисковая система",
        refreshWhenError: "Ошибка чтения, нажмите для перезагрузки",
        switchSlide: "Переключить нижнюю панель",
        viewmore: "Развернуть больше",
        countDown: "Обратный отсчёт",
        customLang: "Язык",
        defaultLang: "Автовыбор",
        hideIcon: "Скрыть иконку",
        initShow: "Инвертировать сочетания клавиш, предпросмотр отображается по умолчанию",
        stayOut: "Сделать так, чтобы плавающая панель отображалась за пределами изображения",
        galleryDownloadGap: "Интервал скачивания",
        galleryDisableArrow: "Отключить клавиши со стрелками"
    }
},
{
    name: "Türkçe",
    match: ["tr", "tr-TR"],
    lang: {
        //Turkish by PUFF1N.
        saveBtn: "Tamam",
        saveName: "İsmi kaydet",
        saveNameTip: "Görüntüleri isimle kaydet",
        default: "Varsayılan",
        textFirst: "Varsa önce bilgi",
        onlyUrl: "Yalnızca URL ile",
        urlAndText: "URL + Bilgi",
        download: "İndir",
        saveBtnTips: "bazı ayarların etkili olabilmesi için sayfanın yenilenmesi gerekir",
        additionalFeature: "Ek özellikler, alta basıldığında etkinleşir",
        invertAdditionalFeature: "Kısayol tuşlarını ters çevir, varsayılan olarak ek özellikleri kullan",
        copy: "Bağlantıyı kopyala",
        copyImg: "Görüntü verilerini kopyala",
        openInNewTab: "Yeni Sekmede Aç",
        closeBtn: "İptal Et",
        invertBtn: "Tersine Çevir",
        compareBtn: "Kıyaslamak",
        closeBtnTips: "bu ayarı iptal et ve tüm ayarları varsayılan haline döndür",
        resetLink: "Ayarları varsayılana döndür",
        resetLinkTips: "tüm ayarları varsayılan değerlerine döndürür",
        share: "Paylaş",
        suitLongImg: "Uzun resimleri kaydırma penceresine oturt",
        globalkeys: "Önizleme için evrensel tuşlar: ",
        globalkeysPress: "Önizlemeyi değiştirmek için basın",
        globalkeysHold: "Önizlemeyi aktif etmek için basılı tutun",
        globalkeysType: "Önizlemeyi etkinleştirme yöntemi",
        closeAfterPreview: "Resim penceresini önizlemeden sonra kapatın",
        loadAll: "Daha fazla sayfa yükle",
        loadedAll: "Yükleme tamamlandı",
        loading: "Yükleniyor ...",
        loadAllTip: "Resmi sonraki sayfaya yükleyin",
        viewmoreEndless: "Daha Fazla Gör'deyken aşağı kaydırınca daha çok resim yükleyin",
        fiddle: "Yönetin",
        fiddleTip: "Daha kompleks işlemler için açılır resimler",
        addImageUrls: "Resim ekle",
        addImageUrlsTips: "Link ile daha fazla resim ekle",
        closeFirst: "Önce mevcut olan Galeri'yi kapatın",
        collect: "Koleksiyonlar",
        collected: "Koleksiyona eklendi",
        exitCollection: "Koleksiyondan çık",
        exitCollectionTip: "Koleksiyon modundan çıkmak için tıklayın",
        noCollectionYet: "Koleksiyonunda hiç fotoğrafın yok",
        collectDetail: "Açıklama",
        collectDetailTip: "Favori resimlerine açıklama ekle",
        playSlide: "Sunu gösterisini oynat",
        slideGap: "Aralık (lar)",
        slideGapTip: "Aralık, birim (saniye)",
        slideBack: "Geri",
        slideBackTip: "Geriden ileriye doğru oynat",
        slideWait: "Resimlerin okunması için bekleyin",
        slideWaitTip: "Gerisayım her resim okunduktan sonra başlar.",
        slideSkipError: "Hatalı resimleri atla",
        slideSkipErrorTip: "Hızlıca okunma hatası olan resimleri atlayın",
        type: "Kategoriler",
        typeTip: "Resim kategorisini seçin",
        showWithRules: "Kurallı simge göstermeye zorla",
        showWithRulesTip: "Resmin boyutu ne olursa olsun kuralla uyuşuyorsa simgeyi göster",
        advancedRules: "Gelişmiş Kurallar",
        advancedRulesTip: "Gelişmiş kurallarla uyuşanlar",
        tpRules: "Joker karakter kuralları",
        tpRulesTip: "Joker karakter kurallarıyla uyuşanlar",
        scaleRules: "Yakınlaştırma",
        scaleRulesTip: "Otomatik olarak bulunan ama ölçeklendirilmiş görüntü",
        noScaleRules: "Ölçeklendirme yok",
        noScaleRulesTip: "Otomatik olarak bulunan ama ölçeklendirilmemiş görüntü",
        smallRules: "Küçük boyut",
        smallRulesTip: "Yüksekliği ve genişliğin gerçek boyutu #t# pikselden az olan küçük boyutlu görüntü.",
        lockSizeTip: "Maksimum büyüklüğü kilitle",
        command: "Komut",
        commandTip: "Komut Menüsü",
        onlineEdit: "Fotoğrafı çevrimiçi düzenle",
        onlineEditTip: "#t# kullanarak bu resmi çevrimiçi olarak düzenleyin",
        openInNewWindow: "Yeni pencerede aç",
        openInNewWindowTip: "Resmi yeni pencerede aç",
        findInPage: "Sayfada bul",
        findInPageTip: "Sayfadaki seçili resme doğru kaydırın",
        viewCollection: "Koleksiyonları görüntüle",
        viewCollectionTip: "Koleksiyonlara eklenmiş tüm resimleri gör",
        inCollection: "Koleksiyon moduyla kullanılamıyor",
        cantFind: "Resim dökümanda değil, ya da gizlenmiş ve yeri bulunamıyor!",
        exportImages: "Tüm Resimleri dışa aktar",
        exportImagesTip: "Gösterilen tüm yüksek boyutlu resimleri yeni pencereye aktar",
        downloadImage: "Gösterilenlerin tümünü indir",
        downloadImageTip: "Şu anda gösterilen tüm resimleri indirin",
        copyImagesUrl: "Tüm resimlerin linkini kopyalayın",
        copyImagesUrlTip: "Yüksek boyutlu olarak gösterilen tüm resimlerin linkini kopyalayın",
        copySuccess: "#t# tane link başarıyla kopyalandı",
        autoRefresh: "Sayfayı otomatik olarak yükle",
        autoRefreshTip: "Kalan son birkaç resim görüntülendiğinde, web sayfalarının yeni resimleri yüklemesi için pencereyi en alta kaydırın.",
        enterFullsc: "Tam ekrana geçin",
        exitFullsc: "Tam ekrandan çıkın",
        config: "Ayarlar",
        openConfig: "Ayarları Açın",
        closeGallery: "Galeriyi kapatın",
        returnToGallery: "Galeriye geri dönün",
        picInfo: "Değiştirmek için tıklayın",
        picNote: "Resim ek açıklaması",
        urlFilter: "Link süzgeçi",
        urlFilterTip: "Linkleri süzgeçten geçirmek için anahtar kelimeleri veya normal ifadeleri girin",
        resolution: "Görüntü Çözünürlüğü",
        picNum: "Resimlerin sayısı",
        picTips: "CTRL tuşuyla resimleri görün",
        savePageTips: "Bu sayfayı tüm resimleri indirmek için kaydet",
        scaleRatio: "Ölçekleme oranı",
        similarImage: "Görsel arama",
        scale: "Yakınlaştır",
        horizontalFlip: "Yatay çevir",
        verticalFlip: "Dikey çevir",
        actualBtn: "Kaynağı görüntüle (A)",
        searchBtn: "Kaynak resmi bul (S)",
        galleryBtn: "Galeriyi gör (G)",
        currentBtn: "Mevcut olanı görüntüle (C)",
        magnifierBtn: "Büyüteç / Yakınlaştırma (M)",
        picTitle: "Resim Başlığı",
        exportImagesUrl: "Resim Linkini dışa aktar",
        exportImagesUrlPop: "Linki kopyalamak için Ctrl+C'yi kullan",
        beginSearchImg: "#t# ile Görsel Arama'yı başlat ...",
        findNoPic: "Kaynak resim bulunamadı",
        findOverBeginLoad: "#t# haritanın sonu, #t# ile eşleşen resimleri bul, ilkini yüklemeye başla",
        loadNextSimilar: "Kaynak resim yüklenemedi, sonraki sonucu yüklemeyi deneyin...",
        loadError: "Yükleme başarısız",
        openHomePage: "Ana Sayfa'yı aç",
        position: "Görüntüleme konumu",
        positionTips: "Gizlemek için ALT tuşuna basılı tutun",
        topLeft: "Resmin sol üst köşesi",
        topRight: "Resmin sağ üst köşesi",
        bottomRight: "Resmin sağ alt köşesi",
        bottomLeft: "Resmin sol alt köşesi",
        topCenter: "Resmin yanı",
        bottomCenter: "Resmin altı",
        floatBar: "Araç Çubuğu",
        previewFollowMouse: "Farenin yanında ön izlemeyi göster",
        showDelay: "Gecikmeyi göster",
        ms: "milisaniye",
        hide: "Gizle",
        hideDelay: "Gecikmeyi gizle",
        forceShow: "Bu boyutun üstündeki yakınlaştırılmamış resimlerde araç çubuğunu göster, ",
        forceShowTip: "Ölçeklendirilmemiş görüntünün boyutu aşağıda ayarlanan büyüklüğü aştığında kayan araç çubuğunu göster",
        sizeLimitOr: "Yalnızca yükseklik YA DA genişlikten etkilenir",
        px: "piksel",
        minSizeLimit: "Bu boyutun üstündeki yakınlaştırılmış resimlerde araç çubuğunu göster",
        minSizeLimitTip: "Görüntü ölçeklendirildikten sonra (görüntünün orijinal boyutu gerçek boyutla eşleşmez), gösterilen görüntünün uzunluğu ayarlanmış değerden büyük olduğunda kayan araç çubuğu görüntülenir.",
        defaultSizeLimit: "Galeri için varsayılan boyut limiti",
        listenBg: "Arka plan resmi dinleme",
        backgroundColor: "Arka plan rengi",
        listenBgTip: "Öğede, araç çubuğunu arka plan resmiyle beraber göster",
        butonOrder: "Araç çubuğu simgelerinin sıralaması",
        keysEnable: "Kısayolu aktif et",
        keysActual: "Resmi büyük aç",
        keysActualTip: "Kayan araç çubuğu göründüğünde resmi büyük olarak açmak için bu düğmeye tıklayın",
        keysSearch: "Kaynak resmi bulun",
        keysSearchTip: "Kayan araç çubuğu göründüğünde kaynak resmi bulmak için bu düğmeye tıklayın",
        headSearchTip: "Görsel arama",
        headSearchAll: "Hepsini Ara",
        keysCurrent: "Mevcut olan resmi açın",
        keysCurrentTip: "Kayan araç çubuğu göründüğünde mevcut görüntüyü açmak için bu düğmeye tıklayın",
        keysMagnifier: "Gözlemlemek için büyüteçi açın",
        keysMagnifierTip: "Kayan araç çubuğu göründüğünde büyüteçi açmak için bu düğmeye tıklayın",
        keysGallery: "Galeri'yi açın (Evrensel tuş ile fonksiyon tuşuna basın)",
        keysGalleryTip: "Kayan araç çubuğu göründüğünde Galeri'yi açmak için bu düğmeye tıklayın",
        openGallery: "Galeri'yi Açın",
        magnifier: "Yakınlaştır",
        magnifierRadius: "Varsayılan yarıçap",
        magnifierWheelZoomEnabled: "Fare tekerleğiyle yakınlaştırmayı etinleştir",
        magnifierWheelZoomRange: "Büyüteç için yakınlaştırma oranı",
        gallery: "Galeri",
        galleryFitToScreen: "Görüntüyü ekrana sığacak şekilde ölçeklendir",
        galleryFitToScreenSmall: "Ayrıca küçük resmi de ölçeklendir",
        galleryFitToScreenTip: "İçine almak için uygulayın, çevrelemek için değil",
        galleryScrollEndToChange: "Uzun resim sonuna kadar kaydırıldıkta sonra resmi değiştir",
        galleryScrollEndToChangeTip: "Önceki seçenek iptal edilirse geçerlidir",
        galleryExportType: "Görüntüler dışarı aktarıldığında ki varsayılan sıralama",
        grid: "Karo sıralama",
        gridBig: "Özgün sıralama",
        list: "Liste sıralaması",
        galleryAutoLoad: "Sonraki sayfada otomatik olarak daha fazla resim yükle",
        galleryLoadAll: "Daha fazla resim yüklerken tüm sayfaları otomatik olarak işleyin",
        galleryLoadAllTip: "Çok fazla sayfa deneyiminizi etkileyebilir",
        galleryDownloadWithZip: "Hepsini indirirken ZIP olarak arşivle",
        galleryDownloadWithZipAlert: "Arşivleniyor, lütfen bir süre bekleyin",
        galleryScaleSmallSize1: "Gerçek boyut yükseklik ve genişlikten daha az",
        galleryScaleSmallSize2: "Pikseller küçük boyutlu resimler halinde gruplandırılır",
        galleryShowSmallSize: "Varsayılan olarak küçük boyutlu resimleri göster",
        galleryTransition: "Galeri değiştiğinde efektleri göster",
        gallerySidebarPosition: "Küçük resim çubuğu konumu",
        bottom: "Alt",
        right: "Sağ",
        left: "Sol",
        top: "Üst",
        gallerySidebarSize: "Yükseklik",
        gallerySidebarSizeTip: "Küçük resim çubuğunun (yatay ise) yüksekliği veya (dikey ise) genişliği",
        galleryMax1: "Maksimum önbellekleme",
        galleryMax2: "Resimler (öncesi ve sonrası)",
        galleryAutoZoom: "Yakınlaştırma %100'e geri döner (Chrome)",
        galleryAutoZoomTip: "Yakınlaştırırsanız, resmin ve kenar araç çubuğu bölümlerinin yakınlaştırmasını tekrar %100'e geri dönderin ve görüntülenebilir alanı artırın (yalnızca Chrome için geçerlidir)",
        galleryDescriptionLength1: "Maksimum açıklama",
        galleryDescriptionLength2: "Karakterler",
        galleryAutoOpenSites: "Her satırda bir tane olmak üzere, otomatik olarak açılan galeri için Linklerin varsayılanları, @ ile Daha Fazla Gör için",
        autoOpenViewmore: "Galeriyi açarken daha fazla görüntüyü otomatik olarak görüntüle",
        galleryViewmoreLayout: "Daha Fazla Gör modunun düzeni",
        gallerySearchData: "Arama için site kuralları, geri yüklemek için boş bırakın",
        galleryEditSite: "Çevrimiçi fotoğraf düzenleme sitesi",
        imgWindow: "Resim Çerçevesi",
        imgWindowFitToScreen: "Ekrana uyarlayın",
        imgWindowFitToScreenTip: "İçine almak için uyarlayın, çevrelemek için değil",
        imgWindowFitToScreenWhenSmall: "Küçükken bile ekrana uyarlayın",
        imgWindowDefaultTool: "Pencereyi açarken varsayılan olarak seçilen araç",
        hand: "El",
        rotate: "Döndür",
        zoom: "Büyüteç",
        imgWindowEscKey: "Kapatmak için Esc'ye basın",
        imgWindowDblClickImgWindow: "Kapatmak için iki kere tıklayın",
        imgWindowClickOutside: "Kapatmak için katmanın üstüne tıklayın",
        imgWindowClickOutsideTip: "Yalnızca Üst Katman gösterildiğinde etkinleştirin",
        none: "Hiçbirisi",
        click: "Tıkla",
        dblclick: "Çift tıkla",
        imgWindowOverlayerShown: "Kaplama",
        imgWindowOverlayerColor: "Renk ve Opaklık",
        imgWindowShiftRotateStep1: "Her seferinde Shift tuşunu basılı tuttuğunuzda döndürün. ",
        imgWindowShiftRotateStep2: "Derece",
        imgWindowMouseWheelZoom: "Fare Tekerleği Yakınlaştırması",
        imgWindowZoomRange: "Yakınlaştırma Aralığı",
        imgWindowZoomRangeTip: "Yakınlaştırma oranı (pozitif olmalıdır)",
        others: "Diğerleri",
        waitImgLoad: "Görüntü yüklenene kadar yakınlaştırma gibi işlemleri gerçekleştirmeye başlayın",
        waitImgLoadTip: "Ctrl tuşunu basılı tutarken, geçici olarak bu ayarın zıttını çalıştırabilirsiniz.",
        debug: "Hata ayıklama modu",
        customRules: "Büyük resim için özel kurallar",
        firstEngine: "Tercih edilen (ilk) arama motoru",
        refreshWhenError: "Okuma hatası, aşırı yüklemek için tıklayın",
        switchSlide: "Kenar çubuğunu değiştir",
        viewmore: "Daha Fazlasını Gör",
        countDown: "Geri Sayım",
        customLang: "Dili Seçin",
        defaultLang: "Otomatik Algılama",
        hideIcon: "Simgeyi gizle",
        initShow: "Varsayılan olarak önizlemeyi göstermek için kısayolu tersine çevir",
        stayOut: "Kayan araç çubuğunun görüntünün dışında kalmasına izin verin",
        galleryDownloadGap: "İndirme aralığı",
        galleryDisableArrow: "Ok tuşlarını devre dışı bırakın"
    }
},
{
    name: "Українська",
    match: ["uk", "uk-UA"],
    lang: {
        //Український переклад by MaSHiNiK.
        saveBtn: "Зберегти",
        saveName: "Назва файлу",
        saveNameTip: "Використовуйте для збереження зображень із оригінальною назвою",
        default: "За замовчуванням",
        textFirst: "Опис спочатку (якщо існує)",
        onlyUrl: "Тільки URL",
        urlAndText: "Посилання + опис файлу",
        download: "Завантажити",
        saveBtnTips: "Щоб деякі параметри вступили в силу, необхідно оновити сторінку.",
        additionalFeature: "Додаткові функції, починають діяти, коли натиснуто клавішу Alt",
        invertAdditionalFeature: "Інвертувати комбінації клавіш, використовувати додаткові функції за замовчуванням",
        copy: "Копіювати посилання",
        copyImg: "Копіювати дані зображення",
        openInNewTab: "Відкрити в новій вкладці",
        closeBtn: "Закрити",
        invertBtn: "Відновити",
        compareBtn: "Порівняти",
        closeBtnTips: "Скасовує ці налаштування та відновлює усі параметри",
        resetLink: "Скинути налаштування",
        resetLinkTips: "Відновлює вміст усіх параметрів до значень за замовчуванням",
        share: "Поділитись",
        suitLongImg: "Відобразити повзунок для занадто довгих зображень",
        globalkeys: "Комбінація клавіш попереднього перегляду:",
        globalkeysPress: "Настиніть, щоб відкрити попередній перегляд",
        globalkeysHold: "Настисніть і утримуйте, щоб відкрити попередній перегляд",
        globalkeysType: "Метод запуску попереднього перегляду:",
        closeAfterPreview: "Закривати вікно зображення, коли попередній перегляд завершено",
        loadAll: "Завантажити більше сторінок",
        loadedAll: "Завантаження завершено",
        loading: "Завантаження",
        loadAllTip: "Завантажити зображеня з наступної сторінки",
        viewmoreEndless: "Прокрутіть сторінку до кінця, щоб автоматично завантажити наступну",
        fiddle: "Спливаюче зображення",
        fiddleTip: "Спливаюче зображення для складних операцій",
        addImageUrls: "Додати зображення",
        addImageUrlsTips: "Додавайте більше зображень з посилання",
        closeFirst: "Спершу закрийте усі поточні галереї.",
        collect: "Додати у колекцію",
        collected: "У колекції",
        exitCollection: "Закрити колекцію",
        exitCollectionTip: "Натисніть, щоб відмінити режим колекціонування",
        noCollectionYet: "У вашій колекції немає жодного зображення",
        collectDetail: "Опис",
        collectDetailTip: "Додайте опис до зображень у колекції",
        playSlide: "Запустити слайд-шоу",
        slideGap: "Інтервал(ів)",
        slideGapTip: "Час інтервалу, у секундах",
        slideBack: "З кінця",
        slideBackTip: "Відтворення від кінця до початку",
        slideWait: "Очікування зчитування зображення",
        slideWaitTip: "Зворотній відлік почнеться тільки коли усі зображення будуть повністю зчитані",
        slideSkipError: "Пропускати зображення з помилками",
        slideSkipErrorTip: "Швидко пропускати зображення, які зчитуються з помилкою",
        type: "Тип",
        typeTip: "Оберіть тип зображень",
        showWithRules: "Примусово відобразити панель інструментів",
        showWithRulesTip: "Показувати іконку, якщо зображення відповідає правилам, незалежно від його розміру",
        advancedRules: "Розширені правила",
        advancedRulesTip: "Відповідає розширеним правилам",
        tpRules: "Правила підставних знаків",
        tpRulesTip: "Відповідає правилу підставних знаків",
        scaleRules: "Масштабовані",
        scaleRulesTip: "JS автоматично виявляє, що зображення на сторінці, були масштабовані",
        noScaleRules: "Без масштабування",
        noScaleRulesTip: "JS автоматично виявляє, що зображення на сторінці, не були масштабовані",
        smallRules: "Невеликий розмір",
        smallRulesTip: "Зображення малого розміру, фактичний розмір висоти та ширини менше #t# пікселів",
        lockSizeTip: "Зафіксувати максимальний розмір",
        command: "Команди",
        commandTip: "Меню команд",
        onlineEdit: "Онлайн-редагування",
        onlineEditTip: "Відредагуйте це зображення онлайн за допомогою #t#",
        openInNewWindow: "Відкрити у новому вікні",
        openInNewWindowTip: "Відкриває зображення у новому вікні",
        findInPage: "Знайти на сторінці",
        findInPageTip: "Прокручує до поточного зображення",
        viewCollection: "Відкрити колекцію",
        viewCollectionTip: "Переглянути усі зображення колекції",
        inCollection: "Недоступно в режимі колекціонування",
        cantFind: "Зображення відсутнє у документі або сховано та не може бути знайдено!",
        exportImages: "Експортувати показані збільшені зображення",
        exportImagesTip: "Експортуйте усі відображувані зображення в нове вікно",
        downloadImage: "Завантажити усі показані",
        downloadImageTip: "Завантажити усі відображувані зображення в поточній галереї",
        copyImagesUrl: "Копіювати збільшені зображення",
        copyImagesUrlTip: "Скопіюйте посилання усіх показаних зображень великого розміру",
        copySuccess: "Посилання збільшеного зображення #t# успішно скопійована",
        autoRefresh: "Автооновлення",
        autoRefreshTip: "Коли дійдете до останніх зображень, прокрутіть головне вікно вниз для автоматичного завантаження нових зображень.",
        enterFullsc: "Повноекранний режим",
        exitFullsc: "Вийти з повноекранного режиму",
        config: "Налаштування",
        openConfig: "Відкрити налаштування",
        closeGallery: "Закрити галерею",
        returnToGallery: "Повернутись у галерею",
        picInfo: "Натисніть, щоб змінити",
        picNote: "Нотатка до зображення",
        urlFilter: "Фільтрувати посилання",
        urlFilterTip: "Введіть ключові слова або регулярні вирази для фільтрації посилань",
        resolution: "Роздільна здатність",
        scaleRatio: "Коефіцієнт масштабування",
        similarImage: "Пошук по зображенню",
        scale: "Масштаб",
        horizontalFlip: "Віддзеркалити по горизонталі",
        verticalFlip: "Віддзеркалити по вертикалі",
        actualBtn: "Відкрити оригінал (А)",
        searchBtn: "Знайти оригінальне зображення (S)",
        galleryBtn: "Відкрити галерею (G)",
        currentBtn: "Відкрити поточне (C)",
        magnifierBtn: "Відкрити лупу (M)",
        picTitle: "Підпис зображення",
        picNum: "Кількість зображень",
        picTips: "Утримуйте Ctrl, щоб збільшити масштаб",
        savePageTips: "Використовуйте «Зберегти сторінку як», щоб зберегти усі зображення",
        exportImagesUrl: "Експорт посилання зображення",
        exportImagesUrlPop: "Натисніть Ctrl+C, щоб скопіювати посилання на зображення",
        beginSearchImg: "Розпізнавання зображення #t#...",
        findNoPic: "Оригінальне зображення не знайдено",
        findOverBeginLoad: "Завершено розпізнавання #t#, усього знайдено #t# відповідних зображень, починаю завантажувати перший...",
        loadNextSimilar: "Не вдалось завантажити оригінальне зображення, спробуйте наступний результат...",
        loadError: "Помилка завантаження",
        openHomePage: "Натисніть тут, щоб відкрити домашню сторінку",
        position: "Розташування плаваючої панелі",
        positionTips: "Щоб приховати, натисніть утримуючи Alt",
        topLeft: "Верхній лівий кут зображення",
        topRight: "Верхній правий кут зображення",
        bottomRight: "Нижній правий кут зображення",
        bottomLeft: "Нижній лівий кут зображення",
        topCenter: "Над зображенням",
        bottomCenter: "Під зображенням",
        floatBar: "Плавуча панель",
        previewFollowMouse: "Показати попередній перегляд поруч з мишкою",
        showDelay: "Затримка перед відображенням",
        ms: "мс.",
        hide: "Приховати",
        hideDelay: "Затримка до приховування",
        forceShow: "Відображати панель інструментів на незбільшених зображеннях",
        forceShowTip: "Показувати плаваючу панель інструментів, коли розмір немасштабованого зображення перевищує встановлений нижче розмір",
        sizeLimitOr: "Впливає лише на висоту або ширину",
        px: "пікс.",
        minSizeLimit: "Масштабувати зображення понад цей розмір для відображення плаваючої панелі",
        minSizeLimitTip: "При масштабуванні зображення (оригінальний розмір якого не спів-падає з фактичним), коли довжина й ширина більше встановленого значення, відображати плаваючу панель.",
        defaultSizeLimit: "Фільтр розміру галереї за замовчуванням",
        listenBg: "Прослуховувати фонові зображення",
        backgroundColor: "Колір фону",
        listenBgTip: "Відображає плаваючу панель на елементі з фоновим зображенням",
        butonOrder: "Сортування іконок плаваючої панелі",
        keysEnable: "Ввімкнути наступні комбінації клавіш",
        keysActual: "Відкрити оригінальне зображення",
        keysActualTip: "Коли з'явиться плаваюча панель, натисніть цю кнопку, щоб відкрити збільшене зображення",
        keysSearch: "Знайти оригінальне зображення",
        keysSearchTip: "Коли з'явиться плаваюча панель, натисніть цю кнопку, щоб знайти оригінальне зображення",
        headSearchTip: "Пошук по зображенню",
        headSearchAll: "Пошук в усіх системах",
        keysCurrent: "Відкрити поточне зображення",
        keysCurrentTip: "Коли з'явиться плаваюча панель, натисніть цю кнопку, щоб відкрити зображення, що відображається в даний момент",
        keysMagnifier: "Відкрити лупу",
        keysMagnifierTip: "Коли з'явиться плаваюча панель, натисніть цю кнопку, щоб відкрити лупу і розглянути зображення",
        keysGallery: "Відкрити галерею (+ функціональні клавіші для глобального)",
        keysGalleryTip: "Коли з'явиться плаваюча панель, натисніть цю кнопку, щоб відкрити галерею",
        openGallery: "Відкрити галерею",
        magnifier: "Лупа",
        magnifierRadius: "Радіус за замовчуванням",
        magnifierWheelZoomEnabled: "Ввімкнути масштабування коліщатком миші",
        magnifierWheelZoomRange: "Множник масштабування коліщатком миші",
        gallery: "Галерея",
        galleryFitToScreen: "Масштабувати зображення під розмір екрану",
        galleryFitToScreenSmall: "Маленькі зображення також масштабуються відповідно до розміру екрана",
        galleryFitToScreenTip: "Метод адаптації - утримувати, а не покривати",
        galleryScrollEndToChange: "Перемкнути зображення після прокрутки до кінця вниз",
        galleryScrollEndToChangeTip: "Працює тільки після скасування попереднього параметра",
        galleryExportType: "Сортування за замовчуванням при експорті зображень",
        grid: "Сітка",
        gridBig: "Оригінальне зображення в сітці",
        list: "Список",
        galleryAutoLoad: "Автозавантажувати більше зображень",
        galleryLoadAll: "Автоматично опрацьовувати усі сторінки при завантаженні більшої кількості зображень",
        galleryLoadAllTip: "Якщо сторінок занадто багато, це може вплинути на швидкість роботи",
        galleryDownloadWithZip: "Завантажувати усе в zip-архіві",
        galleryDownloadWithZipAlert: "Підготовка завантаження, зачекайте декілька секунд",
        galleryScaleSmallSize1: "Якщо висота й ширина фактичного розміру менша",
        galleryScaleSmallSize2: " пікс., то воно класифікується як зображення маленького розміру",
        galleryShowSmallSize: "За замовчуванням відображати зображення маленького розміру",
        galleryTransition: "Показувати ефекти при перемиканні галереї",
        gallerySidebarPosition: "Розташування панелі іконок",
        bottom: "Знизу",
        right: "Справа",
        left: "Зліва",
        top: "Зверху",
        gallerySidebarSize: "Висота",
        gallerySidebarSizeTip: "Висота (при горизонтальному положенні) або ширина (при вертикальному положенні) панелі іконок",
        galleryMax1: "Максимальна кількість для ",
        galleryMax2: " зображень(ня) (до та після)",
        galleryAutoZoom: "Зміна масштабу до 100% (chrome)",
        galleryAutoZoomTip: "Якщо є збільшення, змініть масштаб зображення і бічної панелі назад до 100%, щоб збільшити візуальну область (допустимо тільки в Chrome)",
        galleryDescriptionLength1: "Макс. дожвина коментаря складає",
        galleryDescriptionLength2: " символ(и)",
        galleryAutoOpenSites: "Автовідкривати посилання правил галереї, по одному рядку за раз, і авторозширювати галерею, якщо воно починається з @",
        autoOpenViewmore: "Авторозширювати при відкритті галереї",
        galleryViewmoreLayout: "Макет після розширення галереї",
        gallerySearchData: "Пошук налаштувань сайту, очищення та відновлення",
        galleryEditSite: "Сайт онлайн-редагування",
        imgWindow: "Вікно зображення",
        imgWindowFitToScreen: "Адаптується під розмір екрану і вирівнюється",
        imgWindowFitToScreenTip: "Метод адаптації - contain, а не cover",
        imgWindowFitToScreenWhenSmall: "Навіть маленькі зображення розтягуються під розмір екрану",
        imgWindowDefaultTool: "Інструмент, вибраний за замовчуванням при відкритті вікна",
        hand: "Захват",
        rotate: "Обертання",
        zoom: "Масштаб",
        imgWindowEscKey: "Натисніть Esc для закриття",
        imgWindowDblClickImgWindow: "Двічі клацніть по вікну із зображенням для закриття",
        imgWindowClickOutside: "Клацніть за межами зображення (оверлеєм) для закриття",
        imgWindowClickOutsideTip: "Діє тільки при відображенні оверлея",
        none: "Нічого",
        click: "Клік",
        dblclick: "Подвійний клік",
        imgWindowOverlayerShown: "Оверлей",
        imgWindowOverlayerColor: "Колір й непрозорість",
        imgWindowShiftRotateStep1: "Обертайте, утримуючи клавішу Shift на кожні",
        imgWindowShiftRotateStep2: " градусів",
        imgWindowMouseWheelZoom: "Масштабування колесом прокрутки",
        imgWindowZoomRange: "Масштабування колесом прокрутки",
        imgWindowZoomRangeTip: "Масштабування (має бути додатним числом)",
        others: "Інше",
        waitImgLoad: "Зачекайте, поки зображення повністю завантажиться, перш ніж виконувати такі операції, як масштабування у спливаючому вікні.",
        waitImgLoadTip: "Утримуючи Ctrl, можна тимчасово виконати налаштування, протилежне цьому",
        debug: "Дебаг меню",
        customRules: "Користувацькі правила для великих зображень",
        firstEngine: "Бажана пошукова система",
        refreshWhenError: "Помилка читання, натисніть для перезавантаження",
        switchSlide: "Перемкнути нижню панель",
        viewmore: "Розгорнути більше",
        countDown: "Зворотній відлік",
        customLang: "Мова",
        defaultLang: "Автовибір",
        hideIcon: "Приховати іконку",
        initShow: "Інвертувати комбінацію клавіш для попереднього перегляду за замовчуванням",
        stayOut: "Дозволити плавучій панелі залишитись поза зображенням",
        galleryDownloadGap: "Інтервал завантаження",
        galleryDisableArrow: "Вимкнути клавіші зі стрілками"
    }
}
];
var langList = {};
langData.forEach(lang => {
    langList[lang.match[0]] = lang.name;
});
var i18nData = {};
function setLang(la) {
    i18nData = langData[0].lang;
    for (let i = 0; i < langData.length; i++) {
        let lang = langData[i];
        if (lang && lang.match.indexOf(la) !== -1) {
            i18nData = lang.lang;
            break;
        }
    }
}
